```{r results_biomarker_prep_all, , echo = FALSE, cache = FALSE, results = 'hide', warning = FALSE, message = FALSE, fig.width = 10, eval = TRUE}
## Derive all summaries
summary.biomarkers.all <- list()
summary.biomarkers.all$vte <- dipep_summarise(df           = dipep,
                      	                  grouping     = 'first.st.vte',
                      	                  group.as.col = TRUE,
                                          exclude               = NULL,
                                          exclude.non.recruited = TRUE,
                                          exclude.dvt           = FALSE,
                                          exclude.anti.coag     = FALSE,
                                          exclude.missing       = FALSE,
                      	                  prothombin.time, aptt, clauss.fibrinogen, ddimer.innovance,
                                          thrombin.generation.lag.time, thrombin.generation.endogenous.potential,
                                          thrombin.generation.peak, thrombin.generation.time.to.peak,
                                          ddimer.elisa, plasmin.antiplasmin, prothrombin.fragments,
                                          tissue.factor, troponin, bnp, mrproanp, d.dimer, crp)
summary.biomarkers.all$first.st <- dipep_summarise(df           = dipep,
                      	                  grouping     = 'first.st',
                      	                  group.as.col = TRUE,
                                          exclude               = NULL,
                                          exclude.non.recruited = TRUE,
                                          exclude.dvt           = FALSE,
                                          exclude.anti.coag     = FALSE,
                                          exclude.missing       = FALSE,
                      	                  prothombin.time, aptt, clauss.fibrinogen, ddimer.innovance,
                                          thrombin.generation.lag.time, thrombin.generation.endogenous.potential,
                                          thrombin.generation.peak, thrombin.generation.time.to.peak,
                                          ddimer.elisa, plasmin.antiplasmin, prothrombin.fragments,
                                          tissue.factor, troponin, bnp, mrproanp, d.dimer, crp)
summary.biomarkers.all$second.st <- dipep_summarise(df           = dipep,
                                                grouping     = 'second.st',
                                                group.as.col = TRUE,
                                                exclude               = NULL,
                                                exclude.non.recruited = TRUE,
                                                exclude.dvt           = FALSE,
                                                exclude.anti.coag     = FALSE,
                                                exclude.missing       = FALSE,
                                                prothombin.time, aptt, clauss.fibrinogen, ddimer.innovance,
                                                thrombin.generation.lag.time, thrombin.generation.endogenous.potential,
                                                thrombin.generation.peak, thrombin.generation.time.to.peak,
                                                ddimer.elisa, plasmin.antiplasmin, prothrombin.fragments,
                                                tissue.factor, troponin, bnp, mrproanp, d.dimer, crp)
summary.biomarkers.all$third.st <- dipep_summarise(df           = dipep,
                                               grouping     = 'third.st',
                                               group.as.col = TRUE,
                                               exclude               = NULL,
                                               exclude.non.recruited = TRUE,
                                               exclude.dvt           = FALSE,
                                               exclude.anti.coag     = FALSE,
                                               exclude.missing       = FALSE,
                                               prothombin.time, aptt, clauss.fibrinogen, ddimer.innovance,
                                               thrombin.generation.lag.time, thrombin.generation.endogenous.potential,
                                               thrombin.generation.peak, thrombin.generation.time.to.peak,
                                               ddimer.elisa, plasmin.antiplasmin, prothrombin.fragments,
                                               tissue.factor, troponin, bnp, mrproanp, d.dimer, crp)
summary.biomarkers.all$fourth.st <- dipep_summarise(df           = dipep,
                                                grouping     = 'fourth.st',
                                                group.as.col = TRUE,
                                                exclude               = NULL,
                                                exclude.non.recruited = TRUE,
                                                exclude.dvt           = FALSE,
                                                exclude.anti.coag     = FALSE,
                                                exclude.missing       = FALSE,
                                                prothombin.time, aptt, clauss.fibrinogen, ddimer.innovance,
                                                thrombin.generation.lag.time, thrombin.generation.endogenous.potential,
                                                thrombin.generation.peak, thrombin.generation.time.to.peak,
                                                ddimer.elisa, plasmin.antiplasmin, prothrombin.fragments,
                                                tissue.factor, troponin, bnp, mrproanp, d.dimer, crp)
## Perform Logistic Regression
## Test association of each biomarker
biomarker.all <- list()
## Prothombin (Time)
biomarker.all$prothombin.time <- dipep_glm(df = dipep,
                                           exclude.dvt           = FALSE,
                                           exclude.non.recruited = TRUE,
                                           exclude.anti.coag     = FALSE,
                                           exclude.missing       = FALSE,
                                           classification = 'first.st.vte',
                                           predictor      = 'prothombin.time',
                                           model          = 'Prothombin Time')
biomarker.all$prothombin.time.cat <- dipep_glm(df = dipep,
                                           exclude.dvt           = FALSE,
                                           exclude.non.recruited = TRUE,
                                           exclude.anti.coag     = FALSE,
                                           exclude.missing       = FALSE,
                                           classification = 'first.st.vte',
                                           predictor      = 'prothombin.time.cat',
                                           model          = 'Prothombin Time : Dichotomised')
## APTT
biomarker.all$aptt <- dipep_glm(df = dipep,
                                       exclude.dvt           = FALSE,
                                       exclude.non.recruited = TRUE,
                                       exclude.anti.coag     = FALSE,
                                       exclude.missing       = FALSE,
                                       classification = 'first.st.vte',
                                       predictor      = 'aptt',
                                       model          = 'APTT')
biomarker.all$aptt.cat <- dipep_glm(df = dipep,
                                       exclude.dvt           = FALSE,
                                       exclude.non.recruited = TRUE,
                                       exclude.anti.coag     = FALSE,
                                       exclude.missing       = FALSE,
                                       classification = 'first.st.vte',
                                       predictor      = 'aptt.cat',
                                       model          = 'APTT : Dichotomised')
## Claus Fibrinogen
biomarker.all$clauss.fibrinogen <- dipep_glm(df = dipep,
                                         exclude.dvt           = FALSE,
                                         exclude.non.recruited = TRUE,
                                         exclude.anti.coag     = FALSE,
                                         exclude.missing       = FALSE,
                                         classification = 'first.st.vte',
                                         predictor      = 'clauss.fibrinogen',
                                         model          = 'Clauss Fibrinogen')
biomarker.all$clauss.fibrinogen.cat <- dipep_glm(df = dipep,
                                         exclude.dvt           = FALSE,
                                         exclude.non.recruited = TRUE,
                                         exclude.anti.coag     = FALSE,
                                         exclude.missing       = FALSE,
                                         classification = 'first.st.vte',
                                         predictor      = 'clauss.fibrinogen.cat',
                                         model          = 'Clauss Fibrinogen : Dichotomised')
## D-Dimer - Innovan
biomarker.all$ddimer.innovance <- dipep_glm(df = dipep,
                                exclude.dvt           = FALSE,
                                exclude.non.recruited = TRUE,
                                exclude.anti.coag     = FALSE,
                                exclude.missing       = FALSE,
                                classification = 'first.st.vte',
                                predictor      = 'ddimer.innovance',
                                model          = 'D-Dimer (Innovance)')
biomarker.all$ddimer.innovance.cat <- dipep_glm(df = dipep,
                                exclude.dvt           = FALSE,
                                exclude.non.recruited = TRUE,
                                exclude.anti.coag     = FALSE,
                                exclude.missing       = FALSE,
                                classification = 'first.st.vte',
                                predictor      = 'ddimer.innovance.cat',
                                model          = 'D-Dimer (Innovance) : Dichotomised')
## D-Dimer - ELISA
biomarker.all$ddimer.elisa <- dipep_glm(df = dipep,
                                        exclude.dvt           = FALSE,
                                        exclude.non.recruited = TRUE,
                                        exclude.anti.coag     = FALSE,
                                        exclude.missing       = FALSE,
                                        classification = 'first.st.vte',
                                        predictor      = 'ddimer.elisa',
                                        model          = 'D-Dimer (ELISA)')
biomarker.all$ddimer.elisa.cat <- dipep_glm(df = dipep,
                                            exclude.dvt           = FALSE,
                                            exclude.non.recruited = TRUE,
                                            exclude.anti.coag     = FALSE,
                                            exclude.missing       = FALSE,
                                            classification = 'first.st.vte',
                                            predictor      = 'ddimer.elisa.cat',
                                            model          = 'D-Dimer (ELISA) : Dichotomised')
# Thombin Generation - Lag Time
biomarker.all$thrombin.generation.lag.time <- dipep_glm(df = dipep,
                                                    exclude.dvt           = FALSE,
                                                    exclude.non.recruited = TRUE,
                                                    exclude.anti.coag     = FALSE,
                                                    exclude.missing       = FALSE,
                                                    classification = 'first.st.vte',
                                                    predictor      = 'thrombin.generation.lag.time',
                                                    model          = 'Thrombin Generation (Lag Time)')
## biomarker.all$thrombin.generation.lag.time.cat <- dipep_glm(df = dipep,
##                                                             exclude.dvt           = FALSE,
##                                                             exclude.non.recruited = TRUE,
##                                                             exclude.anti.coag     = FALSE,
##                                                             exclude.missing       = FALSE,
##                                                             classification = 'first.st.vte',
##                                                             predictor      = 'thrombin.generation.lag.time.cat',
##                                                             model          = 'Thrombin Generation (Lag Time) : Dichotomised')
# Thombin Generation - Endogenous Potential
biomarker.all$thrombin.generation.endogenous.potential <- dipep_glm(df = dipep,
                                                                exclude.dvt           = FALSE,
                                                                exclude.non.recruited = TRUE,
                                                                exclude.anti.coag     = FALSE,
                                                                exclude.missing       = FALSE,
                                                                classification = 'first.st.vte',
                                                                predictor      = 'thrombin.generation.endogenous.potential',
                                                                model          = 'Thrombin Generation (Endogenous Potential)')
biomarker.all$thrombin.generation.endogenous.potential.cat <- dipep_glm(df = dipep,
                                                                        exclude.dvt           = FALSE,
                                                                        exclude.non.recruited = TRUE,
                                                                        exclude.anti.coag     = FALSE,
                                                                        exclude.missing       = FALSE,
                                                                        classification = 'first.st.vte',
                                                                        predictor      = 'thrombin.generation.endogenous.potential.cat',
                                                                        model          = 'Thrombin Generation (Endogenous Potential) : Dichotomised')
# Thombin Generation - Peak
biomarker.all$thrombin.generation.peak <- dipep_glm(df = dipep,
                                                    exclude.dvt           = FALSE,
                                                    exclude.non.recruited = TRUE,
                                                    exclude.anti.coag     = FALSE,
                                                    exclude.missing       = FALSE,
                                                    classification = 'first.st.vte',
                                                    predictor      = 'thrombin.generation.peak',
                                                    model          = 'Thrombin Generation (Peak)')
biomarker.all$thrombin.generation.peak.cat <- dipep_glm(df = dipep,
                                                        exclude.dvt           = FALSE,
                                                        exclude.non.recruited = TRUE,
                                                        exclude.anti.coag     = FALSE,
                                                        exclude.missing       = FALSE,
                                                        classification = 'first.st.vte',
                                                        predictor      = 'thrombin.generation.peak.cat',
                                                        model          = 'Thrombin Generation (Peak) : Dichotomised')
# Thombin Generation - Time to Peak
biomarker.all$thrombin.generation.time.to.peak <- dipep_glm(df = dipep,
                                                        exclude.dvt           = FALSE,
                                                        exclude.non.recruited = TRUE,
                                                        exclude.anti.coag     = FALSE,
                                                        exclude.missing       = FALSE,
                                                        classification = 'first.st.vte',
                                                        predictor      = 'thrombin.generation.time.to.peak',
                                                        model          = 'Thrombin Generation (Time to Peak)')
biomarker.all$thrombin.generation.time.to.peak.cat <- dipep_glm(df = dipep,
                                                                exclude.dvt           = FALSE,
                                                                exclude.non.recruited = TRUE,
                                                                exclude.anti.coag     = FALSE,
                                                                exclude.missing       = FALSE,
                                                                classification = 'first.st.vte',
                                                                predictor      = 'thrombin.generation.time.to.peak.cat',
                                                                model          = 'Thrombin Generation (Time to Peak) : Dichotomised')
# Plasmin - Antiplasmin
biomarker.all$plasmin.antiplasmin <- dipep_glm(df = dipep,
                                               exclude.dvt           = FALSE,
                                               exclude.non.recruited = TRUE,
                                               exclude.anti.coag     = FALSE,
                                               exclude.missing       = FALSE,
                                               classification = 'first.st.vte',
                                               predictor      = 'plasmin.antiplasmin',
                                               model          = 'Plasmin-antiplasmin')
biomarker.all$plasmin.antiplasmin.cat <- dipep_glm(df = dipep,
                                                   exclude.dvt           = FALSE,
                                                   exclude.non.recruited = TRUE,
                                                   exclude.anti.coag     = FALSE,
                                                   exclude.missing       = FALSE,
                                                   classification = 'first.st.vte',
                                                   predictor      = 'plasmin.antiplasmin.cat',
                                                   model          = 'Plasmin-antiplasmin : Dichotomised')
# Prothombin Fragments
biomarker.all$prothrombin.fragments <- dipep_glm(df = dipep,
                                                 exclude.dvt           = FALSE,
                                                 exclude.non.recruited = TRUE,
                                                 exclude.anti.coag     = FALSE,
                                                 exclude.missing       = FALSE,
                                                 classification = 'first.st.vte',
                                                 predictor      = 'prothrombin.fragments',
                                                 model          = 'PF 1 + 2')
biomarker.all$prothrombin.fragments.cat <- dipep_glm(df = dipep,
                                                     exclude.dvt           = FALSE,
                                                     exclude.non.recruited = TRUE,
                                                     exclude.anti.coag     = FALSE,
                                                     exclude.missing       = FALSE,
                                                     classification = 'first.st.vte',
                                                     predictor      = 'prothrombin.fragments.cat',
                                                     model          = 'PF 1 + 2 : Dichotomised')
# Tissue Factor
biomarker.all$tissue.factor <- dipep_glm(df = dipep,
                                         exclude.dvt           = FALSE,
                                         exclude.non.recruited = TRUE,
                                         exclude.anti.coag     = FALSE,
                                         exclude.missing       = FALSE,
                                         classification = 'first.st.vte',
                                         predictor      = 'tissue.factor',
                                         model          = 'Tissue Factor')
biomarker.all$tissue.factor.cat <- dipep_glm(df = dipep,
                                             exclude.dvt           = FALSE,
                                             exclude.non.recruited = TRUE,
                                             exclude.anti.coag     = FALSE,
                                             exclude.missing       = FALSE,
                                             classification = 'first.st.vte',
                                             predictor      = 'tissue.factor.cat',
                                             model          = 'Tissue Factor : Dichotomised')
# Troponin
biomarker.all$troponin <- dipep_glm(df = dipep,
                                    exclude.dvt           = FALSE,
                                    exclude.non.recruited = TRUE,
                                    exclude.anti.coag     = FALSE,
                                    exclude.missing       = FALSE,
                                    classification = 'first.st.vte',
                                    predictor      = 'troponin',
                                    model          = 'Troponin')
biomarker.all$troponin.cat <- dipep_glm(df = dipep,
                                    exclude.dvt           = FALSE,
                                    exclude.non.recruited = TRUE,
                                    exclude.anti.coag     = FALSE,
                                    exclude.missing       = FALSE,
                                    classification = 'first.st.vte',
                                    predictor      = 'troponin.cat',
                                    model          = 'Troponin : Dichotomised')
# BNP
biomarker.all$bnp <- dipep_glm(df = dipep,
                               exclude.dvt           = FALSE,
                               exclude.non.recruited = TRUE,
                               exclude.anti.coag     = FALSE,
                               exclude.missing       = FALSE,
                               classification = 'first.st.vte',
                               predictor      = 'bnp',
                               model          = 'BNP')
biomarker.all$bnp.cat <- dipep_glm(df = dipep,
                                   exclude.dvt           = FALSE,
                                   exclude.non.recruited = TRUE,
                                   exclude.anti.coag     = FALSE,
                                   exclude.missing       = FALSE,
                                   classification = 'first.st.vte',
                                   predictor      = 'bnp.cat',
                                   model          = 'BNP : Dichotomised')
# Mrproanp
biomarker.all$mrproanp <- dipep_glm(df = dipep,
                                    exclude.dvt           = FALSE,
                                    exclude.non.recruited = TRUE,
                                    exclude.anti.coag     = FALSE,
                                    exclude.missing       = FALSE,
                                    classification = 'first.st.vte',
                                    predictor      = 'mrproanp',
                                    model          = 'MRProANP')
biomarker.all$mrproanp.cat <- dipep_glm(df = dipep,
                                        exclude.dvt           = FALSE,
                                        exclude.non.recruited = TRUE,
                                        exclude.anti.coag     = FALSE,
                                        exclude.missing       = FALSE,
                                        classification = 'first.st.vte',
                                        predictor      = 'mrproanp.cat',
                                        model          = 'MRProANP : Dichotomised')
## D-Dimer (Hospital) - Binary
biomarker.all$d.dimer.cat <- dipep_glm(df = dipep,
                                    exclude.dvt           = FALSE,
                                    exclude.non.recruited = TRUE,
                                    exclude.anti.coag     = FALSE,
                                    exclude.missing       = FALSE,
                                    classification = 'first.st.vte',
                                    predictor      = 'd.dimer.cat',
                                    model          = 'D-Dimer (Hospital) : Dichotomised')
## D-Dimer (Hospital) - Binary
biomarker.all$d.dimer.gestation.cat <- dipep_glm(df = dipep,
                                    exclude.dvt           = FALSE,
                                    exclude.non.recruited = TRUE,
                                    exclude.anti.coag     = FALSE,
                                    exclude.missing       = FALSE,
                                    classification = 'first.st.vte',
                                    predictor      = 'd.dimer.gestation.cat',
                                    model          = 'D-Dimer (Hospital) : Dichotomised (Gestation Specific)')
## D-Dimer (Hospital) - Continuous
biomarker.all$d.dimer <- dipep_glm(df = dipep,
                                   exclude.dvt           = FALSE,
                                   exclude.non.recruited = TRUE,
                                   exclude.anti.coag     = FALSE,
                                   exclude.missing       = FALSE,
                                   classification = 'first.st.vte',
                                   predictor      = 'd.dimer',
                                   model          = 'D-Dimer (Hospital) : Continuous')
# Crp
biomarker.all$crp <- dipep_glm(df = dipep,
                                    exclude.dvt           = FALSE,
                                    exclude.non.recruited = TRUE,
                                    exclude.anti.coag     = FALSE,
                                    exclude.missing       = FALSE,
                                    classification = 'first.st.vte',
                                    predictor      = 'crp',
                                    model          = 'C-Reactive Protein')
biomarker.all$crp.cat <- dipep_glm(df = dipep,
                                        exclude.dvt           = FALSE,
                                        exclude.non.recruited = TRUE,
                                        exclude.anti.coag     = FALSE,
                                        exclude.missing       = FALSE,
                                        classification = 'first.st.vte',
                                        predictor      = 'crp.cat',
                                        model          = 'C-Reactive Protein : Dichotomised')

## Combine all three sets of tidied output from each model
biomarker.all$tidied <- rbind(biomarker.all$prothombin.time$tidied,
                              biomarker.all$aptt$tidied,
                              biomarker.all$clauss.fibrinogen$tidied,
                              biomarker.all$ddimer.innovance$tidied,
                              biomarker.all$ddimer.elisa$tidied,
                              biomarker.all$thrombin.generation.lag.time$tidied,
                              biomarker.all$thrombin.generation.endogenous.potential$tidied,
                              biomarker.all$thrombin.generation.peak$tidied,
                              biomarker.all$thrombin.generation.time.to.peak$tidied,
                              biomarker.all$plasmin.antiplasmin$tidied,
                              biomarker.all$prothrombin.fragments$tidied,
                              biomarker.all$tissue.factor$tidied,
                              biomarker.all$troponin$tidied,
                              biomarker.all$bnp$tidied,
                              biomarker.all$mrproanp$tidied,
                              biomarker.all$crp$tidied,
                              ## biomarker.all$d.dimer$tidied,
                              biomarker.all$prothombin.time.cat$tidied,
                              biomarker.all$aptt.cat$tidied,
                              biomarker.all$clauss.fibrinogen.cat$tidied,
                              biomarker.all$ddimer.innovance.cat$tidied,
                              biomarker.all$ddimer.elisa.cat$tidied,
                              ## biomarker.all$thrombin.generation.lag.time.cat$tidied,
                              biomarker.all$thrombin.generation.endogenous.potential.cat$tidied,
                              biomarker.all$thrombin.generation.peak.cat$tidied,
                              biomarker.all$thrombin.generation.time.to.peak.cat$tidied,
                              biomarker.all$plasmin.antiplasmin.cat$tidied,
                              biomarker.all$prothrombin.fragments.cat$tidied,
                              biomarker.all$tissue.factor.cat$tidied,
                              biomarker.all$troponin.cat$tidied,
                              biomarker.all$bnp.cat$tidied,
                              biomarker.all$mrproanp.cat$tidied,
                              biomarker.all$crp.cat$tidied,
                              biomarker.all$d.dimer.cat$tidied,
                              biomarker.all$d.dimer.gestation.cat$tidied)
biomarker.all$glance <- rbind(biomarker.all$prothombin.time$glance,
                              biomarker.all$aptt$glance,
                              biomarker.all$clauss.fibrinogen$glance,
                              biomarker.all$ddimer.innovance$glance,
                              biomarker.all$ddimer.elisa$glance,
                              biomarker.all$thrombin.generation.lag.time$glance,
                              biomarker.all$thrombin.generation.endogenous.potential$glance,
                              biomarker.all$thrombin.generation.peak$glance,
                              biomarker.all$thrombin.generation.time.to.peak$glance,
                              biomarker.all$plasmin.antiplasmin$glance,
                              biomarker.all$prothrombin.fragments$glance,
                              biomarker.all$tissue.factor$glance,
                              biomarker.all$troponin$glance,
                              biomarker.all$bnp$glance,
                              biomarker.all$mrproanp$glance,
                              biomarker.all$crp$glance,
                              ## biomarker.all$d.dimer$glance,
                              biomarker.all$prothombin.time.cat$glance,
                              biomarker.all$aptt.cat$glance,
                              biomarker.all$clauss.fibrinogen.cat$glance,
                              biomarker.all$ddimer.innovance.cat$glance,
                              biomarker.all$ddimer.elisa.cat$glance,
                              ## biomarker.all$thrombin.generation.lag.time.cat$glance,
                              biomarker.all$thrombin.generation.endogenous.potential.cat$glance,
                              biomarker.all$thrombin.generation.peak.cat$glance,
                              biomarker.all$thrombin.generation.time.to.peak.cat$glance,
                              biomarker.all$plasmin.antiplasmin.cat$glance,
                              biomarker.all$prothrombin.fragments.cat$glance,
                              biomarker.all$tissue.factor.cat$glance,
                              biomarker.all$troponin.cat$glance,
                              biomarker.all$bnp.cat$glance,
                              biomarker.all$mrproanp.cat$glance,
                              biomarker.all$crp.cat$glance,
                              biomarker.all$d.dimer.cat$glance,
                              biomarker.all$d.dimer.gestation.cat$glance)
## Combine all predicted
biomarker.all$predicted <- rbind(biomarker.all$prothombin.time$predicted,
                                 biomarker.all$aptt$predicted,
                                 biomarker.all$clauss.fibrinogen$predicted,
                                 biomarker.all$ddimer.innovance$predicted,
                                 biomarker.all$ddimer.elisa$predicted,
                                 biomarker.all$thrombin.generation.lag.time$predicted,
                                 biomarker.all$thrombin.generation.endogenous.potential$predicted,
                                 biomarker.all$thrombin.generation.peak$predicted,
                                 biomarker.all$thrombin.generation.time.to.peak$predicted,
                                 biomarker.all$plasmin.antiplasmin$predicted,
                                 biomarker.all$prothrombin.fragments$predicted,
                                 biomarker.all$tissue.factor$predicted,
                                 biomarker.all$troponin$predicted,
                                 biomarker.all$bnp$predicted,
                                 biomarker.all$mrproanp$predicted,
                                 biomarker.all$crp$predicted,
                                 ## biomarker.all$d.dimer$predicted,
                                 biomarker.all$prothombin.time.cat$predicted,
                                 biomarker.all$aptt.cat$predicted,
                                 biomarker.all$clauss.fibrinogen.cat$predicted,
                                 biomarker.all$ddimer.innovance.cat$predicted,
                                 biomarker.all$ddimer.elisa.cat$predicted,
                                 ## biomarker.all$thrombin.generation.lag.time.cat$predicted,
                                 biomarker.all$thrombin.generation.endogenous.potential.cat$predicted,
                                 biomarker.all$thrombin.generation.peak.cat$predicted,
                                 biomarker.all$thrombin.generation.time.to.peak.cat$predicted,
                                 biomarker.all$plasmin.antiplasmin.cat$predicted,
                                 biomarker.all$prothrombin.fragments.cat$predicted,
                                 biomarker.all$tissue.factor.cat$predicted,
                                 biomarker.all$troponin.cat$predicted,
                                 biomarker.all$bnp.cat$predicted,
                                 biomarker.all$mrproanp.cat$predicted,
                                 biomarker.all$crp.cat$predicted,
                                 biomarker.all$d.dimer.cat$predicted,
                                 biomarker.all$d.dimer.gestation.cat$predicted)
## Combine all tabulations
## biomarker.all$cross.tab <- rbind(biomarker.all$prothombin.time$table,
##                                  biomarker.all$aptt$table,
##                                  biomarker.all$clauss.fibrinogen$table,
##                                  biomarker.all$ddimer.innovance$table,
##                                  biomarker.all$ddimer.elisa$table,
##                                  biomarker.all$thrombin.generation.lag.time$table,
##                                  biomarker.all$thrombin.generation.endogenous.potential$table,
##                                  biomarker.all$thrombin.generation.peak$table,
##                                  biomarker.all$thrombin.generation.time.to.peak$table,
##                                  biomarker.all$plasmin.antiplasmin$table,
##                                  biomarker.all$prothrombin.fragments$table,
##                                  biomarker.all$tissue.factor$table,
##                                  biomarker.all$troponin$table,
##                                  biomarker.all$bnp$table,
##                                  biomarker.all$mrproanp$table,
##                                  biomarker.all$crp$table,
##                                  ## biomarker.all$d.dimer$table,
##                                  biomarker.all$prothombin.time.cat$table,
##                                  biomarker.all$aptt.cat$table,
##                                  biomarker.all$clauss.fibrinogen.cat$table,
##                                  biomarker.all$ddimer.innovance.cat$table,
##                                  biomarker.all$ddimer.elisa.cat$table,
##                                  ## biomarker.all$thrombin.generation.lag.time.cat$table,
##                                  biomarker.all$thrombin.generation.endogenous.potential.cat$table,
##                                  biomarker.all$thrombin.generation.peak.cat$table,
##                                  biomarker.all$thrombin.generation.time.to.peak.cat$table,
##                                  biomarker.all$plasmin.antiplasmin.cat$table,
##                                  biomarker.all$prothrombin.fragments.cat$table,
##                                  biomarker.all$tissue.factor.cat$table,
##                                  biomarker.all$troponin.cat$table,
##                                  biomarker.all$bnp.cat$table,
##                                  biomarker.all$mrproanp.cat$table,
##                                  biomarker.all$crp.cat$table,
##                                  biomarker.all$d.dimer.cat$table,
##                                  biomarker.all$d.dimer.gestation.cat$table)

## Extract the data used from each overall binary dichotomisation and bind into one
## for summarisation using dipep_roc(), required since the $predicted for each
## model has probabilities and dipep_roc() takes these and uses a supplied
## threshold derives sensitivity and specificity
biomarker.all$aptt.cat$fitted$data                              <- dipep_extract_binary(df      = biomarker.all$aptt.cat$fitted$data,
                                                                                                   outcome = 'aptt.cat')
biomarker.all$clauss.fibrinogen.cat$fitted$data                        <- dipep_extract_binary(df      = biomarker.all$clauss.fibrinogen.cat$fitted$data,
                                                                                                   outcome = 'clauss.fibrinogen.cat')
biomarker.all$ddimer.innovance.cat$fitted$data                         <- dipep_extract_binary(df      = biomarker.all$ddimer.innovance.cat$fitted$data,
                                                                                                   outcome = 'ddimer.innovance.cat')
biomarker.all$ddimer.elisa.cat$fitted$data                             <- dipep_extract_binary(df      = biomarker.all$ddimer.elisa.cat$fitted$data,
                                                                                                   outcome = 'ddimer.elisa.cat')
biomarker.all$thrombin.generation.endogenous.potential.cat$fitted$data <- dipep_extract_binary(df      = biomarker.all$thrombin.generation.endogenous.potential.cat$fitted$data,
                                                                                                   outcome = 'thrombin.generation.endogenous.potential.cat')
biomarker.all$thrombin.generation.peak.cat$fitted$data                 <- dipep_extract_binary(df      = biomarker.all$thrombin.generation.peak.cat$fitted$data,
                                                                                                   outcome = 'thrombin.generation.peak.cat')
biomarker.all$thrombin.generation.time.to.peak.cat$fitted$data         <- dipep_extract_binary(df      = biomarker.all$thrombin.generation.time.to.peak.cat$fitted$data,
                                                                                                   outcome = 'thrombin.generation.time.to.peak.cat')
biomarker.all$plasmin.antiplasmin.cat$fitted$data                      <- dipep_extract_binary(df      = biomarker.all$plasmin.antiplasmin.cat$fitted$data,
                                                                                                   outcome = 'plasmin.antiplasmin.cat')
biomarker.all$prothrombin.fragments.cat$fitted$data                    <- dipep_extract_binary(df      = biomarker.all$prothrombin.fragments.cat$fitted$data,
                                                                                                   outcome = 'prothrombin.fragments.cat')
biomarker.all$tissue.factor.cat$fitted$data                            <- dipep_extract_binary(df      = biomarker.all$tissue.factor.cat$fitted$data,
                                                                                                   outcome = 'tissue.factor.cat')
biomarker.all$troponin.cat$fitted$data                                 <- dipep_extract_binary(df      = biomarker.all$troponin.cat$fitted$data,
                                                                                                   outcome = 'troponin.cat')
biomarker.all$bnp.cat$fitted$data                                      <- dipep_extract_binary(df      = biomarker.all$bnp.cat$fitted$data,
                                                                                                   outcome = 'bnp.cat')
biomarker.all$mrproanp.cat$fitted$data                                 <- dipep_extract_binary(df      = biomarker.all$mrproanp.cat$fitted$data,
                                                                                                   outcome = 'mrproanp.cat')
biomarker.all$d.dimer.cat$fitted$data                                  <- dipep_extract_binary(df      = biomarker.all$d.dimer.cat$fitted$data,
                                                                                                          outcome = 'd.dimer.cat')
biomarker.all$d.dimer.gestation.cat$fitted$data                        <- dipep_extract_binary(df      = biomarker.all$d.dimer.gestation.cat$fitted$data,
                                                                                                          outcome = 'd.dimer.gestation.cat')
biomarker.all$crp.cat$fitted$data                                      <- dipep_extract_binary(df      = biomarker.all$crp.cat$fitted$data,
                                                                                                   outcome = 'crp.cat')
biomarker.all$predicted.existing <- rbind(biomarker.all$aptt.cat$fitted$data,
                                          biomarker.all$clauss.fibrinogen.cat$fitted$data,
                                          biomarker.all$ddimer.innovance.cat$fitted$data,
                                          biomarker.all$ddimer.elisa.cat$fitted$data,
                                          biomarker.all$thrombin.generation.endogenous.potential.cat$fitted$data,
                                          biomarker.all$thrombin.generation.peak.cat$fitted$data,
                                          biomarker.all$thrombin.generation.time.to.peak.cat$fitted$data,
                                          biomarker.all$plasmin.antiplasmin.cat$fitted$data,
                                          biomarker.all$prothrombin.fragments.cat$fitted$data,
                                          biomarker.all$tissue.factor.cat$fitted$data,
                                          biomarker.all$troponin.cat$fitted$data,
                                          biomarker.all$bnp.cat$fitted$data,
                                          biomarker.all$mrproanp.cat$fitted$data,
                                          biomarker.all$d.dimer.cat$fitted$data,
                                          biomarker.all$d.dimer.gestation.cat$fitted$data,
                                          biomarker.all$crp.cat$fitted$data) %>%
                               mutate(D = first.st.vte,
                                      M = case_when(.$predictor == 'Normal' ~ 0,
                                                    .$predictor == 'Abnormal'    ~ 1),
                                      term = case_when(.$name == 'aptt.cat' ~ 'APTT : Dichotomised',
                                                       .$name == 'clauss.fibrinogen.cat' ~ 'Clauss Fibrinogen : Dichotomised',
                                                       .$name == 'ddimer.innovance.cat' ~ 'D-Dimer (Innovance) : Dichotomised',
                                                       .$name == 'ddimer.elisa.cat' ~ 'D-Dimer (ELISA) : Dichotomised',
                                                       .$name == 'thrombin.generation.lag.time.cat' ~ 'Thrombin Generation (Lag Time) : Dichotomised',
                                                       .$name == 'thrombin.generation.endogenous.potential.cat' ~ 'Thrombin Generation (Endogenous Potential) : Dichotomised',
                                                       .$name == 'thrombin.generation.peak.cat' ~ 'Thrombin Generation (Peak) : Dichotomised',
                                                       .$name == 'thrombin.generation.time.to.peak.cat' ~ 'Thrombin Generation (Time to Peak) : Dichotomised',
                                                       .$name == 'plasmin.antiplasmin.cat' ~ 'Plasmin-antiplasmin : Dichotomised',
                                                       .$name == 'prothrombin.fragments.cat' ~ 'Prothombin (Time) : Dichotomised',
                                                       .$name == 'tissue.factor.cat' ~ 'Tissue Factor : Dichotomised',
                                                       .$name == 'troponin.cat' ~ 'Troponin : Dichotomised',
                                                       .$name == 'bnp.cat' ~ 'BNP : Dichotomised',
                                                       .$name == 'mrproanp.cat' ~ 'MRproANP : Dichotomised',
                                                       .$name == 'd.dimer.cat' ~ 'D-Dimer (Hospital) : Dichotomised',
                                                       .$name == 'd.dimer.gestation.cat' ~ 'D-Dimer (Hospital) : Dichotomised (Gestation Specific)',
                                                       .$name == 'crp.cat' ~ 'C-Reactive Protein : Dichotomised')) %>%
                              dplyr::select(D, predictor, M, name, term)

```

```{r results_biomarker_prep_excl_anti_coag, , echo = FALSE, cache = FALSE, results = 'hide', warning = FALSE, message = FALSE, fig.width = 10, eval = TRUE}
summary.biomarkers.excl.anti.coag <- list()
summary.biomarkers.excl.anti.coag$vte <- dipep_summarise(df           = dipep,
                      	                  grouping     = 'first.st.vte',
                      	                  group.as.col = TRUE,
                                          exclude               = NULL,
                                          exclude.non.recruited = TRUE,
                                          exclude.dvt           = FALSE,
                                          exclude.anti.coag     = TRUE,
                                          exclude.missing       = FALSE,
                      	                  prothombin.time, aptt, clauss.fibrinogen, ddimer.innovance,
                                          thrombin.generation.lag.time, thrombin.generation.endogenous.potential,
                                          thrombin.generation.peak, thrombin.generation.time.to.peak,
                                          ddimer.elisa, plasmin.antiplasmin, prothrombin.fragments,
                                          tissue.factor, troponin, bnp, mrproanp, d.dimer, crp)
summary.biomarkers.excl.anti.coag$first.st <- dipep_summarise(df           = dipep,
                      	                  grouping     = 'first.st',
                      	                  group.as.col = TRUE,
                                          exclude               = NULL,
                                          exclude.non.recruited = TRUE,
                                          exclude.dvt           = FALSE,
                                          exclude.anti.coag     = TRUE,
                                          exclude.missing       = FALSE,
                      	                  prothombin.time, aptt, clauss.fibrinogen, ddimer.innovance,
                                          thrombin.generation.lag.time, thrombin.generation.endogenous.potential,
                                          thrombin.generation.peak, thrombin.generation.time.to.peak,
                                          ddimer.elisa, plasmin.antiplasmin, prothrombin.fragments,
                                          tissue.factor, troponin, bnp, mrproanp, d.dimer, crp)
summary.biomarkers.excl.anti.coag$second.st <- dipep_summarise(df           = dipep,
                                                grouping     = 'second.st',
                                                group.as.col = TRUE,
                                                exclude               = NULL,
                                                exclude.non.recruited = TRUE,
                                                exclude.dvt           = FALSE,
                                                exclude.anti.coag     = TRUE,
                                                exclude.missing       = FALSE,
                                                prothombin.time, aptt, clauss.fibrinogen, ddimer.innovance,
                                                thrombin.generation.lag.time, thrombin.generation.endogenous.potential,
                                                thrombin.generation.peak, thrombin.generation.time.to.peak,
                                                ddimer.elisa, plasmin.antiplasmin, prothrombin.fragments,
                                                tissue.factor, troponin, bnp, mrproanp, d.dimer, crp)
summary.biomarkers.excl.anti.coag$third.st <- dipep_summarise(df           = dipep,
                                               grouping     = 'third.st',
                                               group.as.col = TRUE,
                                               exclude               = NULL,
                                               exclude.non.recruited = TRUE,
                                               exclude.dvt           = FALSE,
                                               exclude.anti.coag     = TRUE,
                                               exclude.missing       = FALSE,
                                               prothombin.time, aptt, clauss.fibrinogen, ddimer.innovance,
                                               thrombin.generation.lag.time, thrombin.generation.endogenous.potential,
                                               thrombin.generation.peak, thrombin.generation.time.to.peak,
                                               ddimer.elisa, plasmin.antiplasmin, prothrombin.fragments,
                                               tissue.factor, troponin, bnp, mrproanp, d.dimer, crp)
summary.biomarkers.excl.anti.coag$fourth.st <- dipep_summarise(df           = dipep,
                                                grouping     = 'fourth.st',
                                                group.as.col = TRUE,
                                                exclude               = NULL,
                                                exclude.non.recruited = TRUE,
                                                exclude.dvt           = FALSE,
                                                exclude.anti.coag     = TRUE,
                                                exclude.missing       = FALSE,
                                                prothombin.time, aptt, clauss.fibrinogen, ddimer.innovance,
                                                thrombin.generation.lag.time, thrombin.generation.endogenous.potential,
                                                thrombin.generation.peak, thrombin.generation.time.to.peak,
                                                ddimer.elisa, plasmin.antiplasmin, prothrombin.fragments,
                                                tissue.factor, troponin, bnp, mrproanp, d.dimer, crp)
## Test association of each biomarker
biomarker.excl.anti.coag <- list()
## Prothombin Time
biomarker.excl.anti.coag$prothombin.time <- dipep_glm(df = dipep,
                                                      exclude.dvt           = FALSE,
                                                      exclude.non.recruited = TRUE,
                                                      exclude.anti.coag     = TRUE,
                                                      exclude.missing       = FALSE,
                                                      classification = 'first.st.vte',
                                                      predictor      = 'prothombin.time',
                                                      model          = 'Prothombin Time')
biomarker.excl.anti.coag$prothombin.time.cat <- dipep_glm(df = dipep,
                                                      exclude.dvt           = FALSE,
                                                      exclude.non.recruited = TRUE,
                                                      exclude.anti.coag     = TRUE,
                                                      exclude.missing       = FALSE,
                                                      classification = 'first.st.vte',
                                                      predictor      = 'prothombin.time.cat',
                                                      model          = 'Prothombin Time : Dichotomised')
## APTT
biomarker.excl.anti.coag$aptt <- dipep_glm(df = dipep,
                                           exclude.dvt           = FALSE,
                                           exclude.non.recruited = TRUE,
                                           exclude.anti.coag     = TRUE,
                                           exclude.missing       = FALSE,
                                           classification = 'first.st.vte',
                                           predictor      = 'aptt',
                                           model          = 'APTT')
biomarker.excl.anti.coag$aptt.cat <- dipep_glm(df = dipep,
                                               exclude.dvt           = FALSE,
                                               exclude.non.recruited = TRUE,
                                               exclude.anti.coag     = TRUE,
                                               exclude.missing       = FALSE,
                                               classification = 'first.st.vte',
                                               predictor      = 'aptt.cat',
                                               model          = 'APTT : Dichotomised')
## Claus Fibrinogen
biomarker.excl.anti.coag$clauss.fibrinogen <- dipep_glm(df = dipep,
                                                        exclude.dvt           = FALSE,
                                                        exclude.non.recruited = TRUE,
                                                        exclude.anti.coag     = TRUE,
                                                        exclude.missing       = FALSE,
                                                        classification = 'first.st.vte',
                                                        predictor      = 'clauss.fibrinogen',
                                                        model          = 'Clauss Fibrinogen')
biomarker.excl.anti.coag$clauss.fibrinogen.cat <- dipep_glm(df = dipep,
                                                            exclude.dvt           = FALSE,
                                                            exclude.non.recruited = TRUE,
                                                            exclude.anti.coag     = TRUE,
                                                            exclude.missing       = FALSE,
                                                            classification = 'first.st.vte',
                                                            predictor      = 'clauss.fibrinogen.cat',
                                                            model          = 'Clauss Fibrinogen : Dichotomised')
## D-Dimer - Innovance
biomarker.excl.anti.coag$ddimer.innovance <- dipep_glm(df = dipep,
                                                       exclude.dvt           = FALSE,
                                                       exclude.non.recruited = TRUE,
                                                       exclude.anti.coag     = TRUE,
                                                       exclude.missing       = FALSE,
                                                       classification = 'first.st.vte',
                                                       predictor      = 'ddimer.innovance',
                                                       model          = 'D-Dimer (Innovance)')
biomarker.excl.anti.coag$ddimer.innovance.cat <- dipep_glm(df = dipep,
                                                           exclude.dvt           = FALSE,
                                                           exclude.non.recruited = TRUE,
                                                           exclude.anti.coag     = TRUE,
                                                           exclude.missing       = FALSE,
                                                           classification = 'first.st.vte',
                                                           predictor      = 'ddimer.innovance.cat',
                                                           model          = 'D-Dimer (Innovance) : Dichotomised')
## D-Dimer - ELISA
biomarker.excl.anti.coag$ddimer.elisa <- dipep_glm(df = dipep,
                                                   exclude.dvt           = FALSE,
                                                   exclude.non.recruited = TRUE,
                                                   exclude.anti.coag     = TRUE,
                                                   exclude.missing       = FALSE,
                                                   classification = 'first.st.vte',
                                                   predictor      = 'ddimer.elisa',
                                                   model          = 'D-Dimer (ELISA)')
biomarker.excl.anti.coag$ddimer.elisa.cat <- dipep_glm(df = dipep,
                                                       exclude.dvt           = FALSE,
                                                       exclude.non.recruited = TRUE,
                                                       exclude.anti.coag     = TRUE,
                                                       exclude.missing       = FALSE,
                                                       classification = 'first.st.vte',
                                                       predictor      = 'ddimer.elisa.cat',
                                                       model          = 'D-Dimer (ELISA) : Dichotomised')
# Thombin Generation - Lag Time
biomarker.excl.anti.coag$thrombin.generation.lag.time <- dipep_glm(df = dipep,
                                                                   exclude.dvt           = FALSE,
                                                                   exclude.non.recruited = TRUE,
                                                                   exclude.anti.coag     = TRUE,
                                                                   exclude.missing       = FALSE,
                                                                   classification = 'first.st.vte',
                                                                   predictor      = 'thrombin.generation.lag.time',
                                                                   model          = 'Thrombin Generation (Lag Time)')
## biomarker.excl.anti.coag$thrombin.generation.lag.time.cat <- dipep_glm(df = dipep,
##                                                                        exclude.dvt           = FALSE,
##                                                                        exclude.non.recruited = TRUE,
##                                                                        exclude.anti.coag     = TRUE,
##                                                                        exclude.missing       = FALSE,
##                                                                        classification = 'first.st.vte',
##                                                                        predictor      = 'thrombin.generation.lag.time.cat',
##                                                                        model          = 'Thrombin Generation (Lag Time) : Dichotomised')
# Thombin Generation - Endogenous Potential
biomarker.excl.anti.coag$thrombin.generation.endogenous.potential <- dipep_glm(df = dipep,
                                                                               exclude.dvt           = FALSE,
                                                                               exclude.non.recruited = TRUE,
                                                                               exclude.anti.coag     = TRUE,
                                                                               exclude.missing       = FALSE,
                                                                               classification = 'first.st.vte',
                                                                               predictor      = 'thrombin.generation.endogenous.potential',
                                                                               model          = 'Thrombin Generation (Endogenous Potential)')
biomarker.excl.anti.coag$thrombin.generation.endogenous.potential.cat <- dipep_glm(df = dipep,
                                                                                   exclude.dvt           = FALSE,
                                                                                   exclude.non.recruited = TRUE,
                                                                                   exclude.anti.coag     = TRUE,
                                                                                   exclude.missing       = FALSE,
                                                                                   classification = 'first.st.vte',
                                                                                   predictor      = 'thrombin.generation.endogenous.potential.cat',
                                                                                   model          = 'Thrombin Generation (Endogenous Potential) : Dichotomised')
# Thombin Generation - Peak
biomarker.excl.anti.coag$thrombin.generation.peak <- dipep_glm(df = dipep,
                                                               exclude.dvt           = FALSE,
                                                               exclude.non.recruited = TRUE,
                                                               exclude.anti.coag     = TRUE,
                                                               exclude.missing       = FALSE,
                                                               classification = 'first.st.vte',
                                                               predictor      = 'thrombin.generation.peak',
                                                               model          = 'Thrombin Generation (Peak)')
biomarker.excl.anti.coag$thrombin.generation.peak.cat <- dipep_glm(df = dipep,
                                                                   exclude.dvt           = FALSE,
                                                                   exclude.non.recruited = TRUE,
                                                                   exclude.anti.coag     = TRUE,
                                                                   exclude.missing       = FALSE,
                                                                   classification = 'first.st.vte',
                                                                   predictor      = 'thrombin.generation.peak.cat',
                                                                   model          = 'Thrombin Generation (Peak) : Dichotomised')
# Thombin Generation - Time to Peak
biomarker.excl.anti.coag$thrombin.generation.time.to.peak <- dipep_glm(df = dipep,
                                                                       exclude.dvt           = FALSE,
                                                                       exclude.non.recruited = TRUE,
                                                                       exclude.anti.coag     = TRUE,
                                                                       exclude.missing       = FALSE,
                                                                       classification = 'first.st.vte',
                                                                       predictor      = 'thrombin.generation.time.to.peak',
                                                                       model          = 'Thrombin Generation (Time to Peak)')
biomarker.excl.anti.coag$thrombin.generation.time.to.peak.cat <- dipep_glm(df = dipep,
                                                                           exclude.dvt           = FALSE,
                                                                           exclude.non.recruited = TRUE,
                                                                           exclude.anti.coag     = TRUE,
                                                                           exclude.missing       = FALSE,
                                                                           classification = 'first.st.vte',
                                                                           predictor      = 'thrombin.generation.time.to.peak.cat',
                                                                           model          = 'Thrombin Generation (Time to Peak) : Dichotomised')
# Plasmin - Antiplasmin
biomarker.excl.anti.coag$plasmin.antiplasmin <- dipep_glm(df = dipep,
                                                          exclude.dvt           = FALSE,
                                                          exclude.non.recruited = TRUE,
                                                          exclude.anti.coag     = TRUE,
                                                          exclude.missing       = FALSE,
                                                          classification = 'first.st.vte',
                                                          predictor      = 'plasmin.antiplasmin',
                                                          model          = 'Plasmin-antiplasmin')
biomarker.excl.anti.coag$plasmin.antiplasmin.cat <- dipep_glm(df = dipep,
                                                              exclude.dvt           = FALSE,
                                                              exclude.non.recruited = TRUE,
                                                              exclude.anti.coag     = TRUE,
                                                              exclude.missing       = FALSE,
                                                              classification = 'first.st.vte',
                                                              predictor      = 'plasmin.antiplasmin.cat',
                                                              model          = 'Plasmin-antiplasmin : Dichotomised')
# Prothombin Fragments
biomarker.excl.anti.coag$prothrombin.fragments <- dipep_glm(df = dipep,
                                                            exclude.dvt           = FALSE,
                                                            exclude.non.recruited = TRUE,
                                                            exclude.anti.coag     = TRUE,
                                                            exclude.missing       = FALSE,
                                                            classification = 'first.st.vte',
                                                            predictor      = 'prothrombin.fragments',
                                                            model          = 'PF 1 + 2')
biomarker.excl.anti.coag$prothrombin.fragments.cat <- dipep_glm(df = dipep,
                                                                exclude.dvt           = FALSE,
                                                                exclude.non.recruited = TRUE,
                                                                exclude.anti.coag     = TRUE,
                                                                exclude.missing       = FALSE,
                                                                classification = 'first.st.vte',
                                                                predictor      = 'prothrombin.fragments.cat',
                                                                model          = 'PF 1 + 2 : Dichotomised')
# Soluble Tissue Factor
biomarker.excl.anti.coag$tissue.factor <- dipep_glm(df = dipep,
                                                    exclude.dvt           = FALSE,
                                                    exclude.non.recruited = TRUE,
                                                    exclude.anti.coag     = TRUE,
                                                    exclude.missing       = FALSE,
                                                    classification = 'first.st.vte',
                                                    predictor      = 'tissue.factor',
                                                    model          = 'Soluble Tissue Factor')
biomarker.excl.anti.coag$tissue.factor.cat <- dipep_glm(df = dipep,
                                                        exclude.dvt           = FALSE,
                                                        exclude.non.recruited = TRUE,
                                                        exclude.anti.coag     = TRUE,
                                                        exclude.missing       = FALSE,
                                                        classification = 'first.st.vte',
                                                        predictor      = 'tissue.factor.cat',
                                                        model          = 'Soluble Tissue Factor : Dichotomised')
# Troponin
biomarker.excl.anti.coag$troponin <- dipep_glm(df = dipep,
                                               exclude.dvt           = FALSE,
                                               exclude.non.recruited = TRUE,
                                               exclude.anti.coag     = TRUE,
                                               exclude.missing       = FALSE,
                                               classification = 'first.st.vte',
                                               predictor      = 'troponin',
                                               model          = 'Troponin')
biomarker.excl.anti.coag$troponin.cat <- dipep_glm(df = dipep,
                                                   exclude.dvt           = FALSE,
                                                   exclude.non.recruited = TRUE,
                                                   exclude.anti.coag     = TRUE,
                                                   exclude.missing       = FALSE,
                                                   classification = 'first.st.vte',
                                                   predictor      = 'troponin.cat',
                                                   model          = 'Troponin : Dichotomised')
# BNP
biomarker.excl.anti.coag$bnp <- dipep_glm(df = dipep,
                                           exclude.dvt           = FALSE,
                                           exclude.non.recruited = TRUE,
                                           exclude.anti.coag     = TRUE,
                                           exclude.missing       = FALSE,
                                           classification = 'first.st.vte',
                                           predictor      = 'bnp',
                                           model          = 'BNP')
biomarker.excl.anti.coag$bnp.cat <- dipep_glm(df = dipep,
                                              exclude.dvt           = FALSE,
                                              exclude.non.recruited = TRUE,
                                              exclude.anti.coag     = TRUE,
                                              exclude.missing       = FALSE,
                                              classification = 'first.st.vte',
                                              predictor      = 'bnp.cat',
                                              model          = 'BNP : Dichotomised')
# Mrproanp
biomarker.excl.anti.coag$mrproanp <- dipep_glm(df = dipep,
                                               exclude.dvt           = FALSE,
                                               exclude.non.recruited = TRUE,
                                               exclude.anti.coag     = TRUE,
                                               exclude.missing       = FALSE,
                                               classification = 'first.st.vte',
                                               predictor      = 'mrproanp',
                                               model          = 'MRProANP')
biomarker.excl.anti.coag$mrproanp.cat <- dipep_glm(df = dipep,
                                               exclude.dvt           = FALSE,
                                               exclude.non.recruited = TRUE,
                                               exclude.anti.coag     = TRUE,
                                               exclude.missing       = FALSE,
                                               classification = 'first.st.vte',
                                               predictor      = 'mrproanp.cat',
                                               model          = 'MRProANP : Dichotomised')
## D-Dimer (Hospital) - Binary
biomarker.excl.anti.coag$d.dimer.cat <- dipep_glm(df = dipep,
                                    exclude.dvt           = FALSE,
                                    exclude.non.recruited = TRUE,
                                    exclude.anti.coag     = TRUE,
                                    exclude.missing       = FALSE,
                                    classification = 'first.st.vte',
                                    predictor      = 'd.dimer.cat',
                                    model          = 'D-Dimer (Hospital) : Dichotomised')
## D-Dimer (Hospital) - Continuous
biomarker.excl.anti.coag$d.dimer <- dipep_glm(df = dipep,
                                   exclude.dvt           = FALSE,
                                   exclude.non.recruited = TRUE,
                                   exclude.anti.coag     = TRUE,
                                   exclude.missing       = FALSE,
                                   classification = 'first.st.vte',
                                   predictor      = 'd.dimer',
                                   model          = 'D-Dimer (Hospital) : Continuous')
## D-Dimer (Hospital) - Binary (Gestation)
biomarker.excl.anti.coag$d.dimer.gestation.cat <- dipep_glm(df = dipep,
                                    exclude.dvt           = FALSE,
                                    exclude.non.recruited = TRUE,
                                    exclude.anti.coag     = TRUE,
                                    exclude.missing       = FALSE,
                                    classification = 'first.st.vte',
                                    predictor      = 'd.dimer.gestation.cat',
                                    model          = 'D-Dimer (Hospital) : Dichotomised (Gestation Specific)')
# Crp
biomarker.excl.anti.coag$crp <- dipep_glm(df = dipep,
                                               exclude.dvt           = FALSE,
                                               exclude.non.recruited = TRUE,
                                               exclude.anti.coag     = TRUE,
                                               exclude.missing       = FALSE,
                                               classification = 'first.st.vte',
                                               predictor      = 'crp',
                                               model          = 'C-Reactive Protein')
biomarker.excl.anti.coag$crp.cat <- dipep_glm(df = dipep,
                                               exclude.dvt           = FALSE,
                                               exclude.non.recruited = TRUE,
                                               exclude.anti.coag     = TRUE,
                                               exclude.missing       = FALSE,
                                               classification = 'first.st.vte',
                                               predictor      = 'crp.cat',
                                               model          = 'C-Reactive Protein : Dichotomised')

## Combine all three sets of tidied output from each model
biomarker.excl.anti.coag$tidied <- rbind(biomarker.excl.anti.coag$prothombin.time$tidied,
                                         biomarker.excl.anti.coag$aptt$tidied,
                                         biomarker.excl.anti.coag$clauss.fibrinogen$tidied,
                                         biomarker.excl.anti.coag$ddimer.innovance$tidied,
                                         biomarker.excl.anti.coag$ddimer.elisa$tidied,
                                         biomarker.excl.anti.coag$thrombin.generation.lag.time$tidied,
                                         biomarker.excl.anti.coag$thrombin.generation.endogenous.potential$tidied,
                                         biomarker.excl.anti.coag$thrombin.generation.peak$tidied,
                                         biomarker.excl.anti.coag$thrombin.generation.time.to.peak$tidied,
                                         biomarker.excl.anti.coag$plasmin.antiplasmin$tidied,
                                         biomarker.excl.anti.coag$prothrombin.fragments$tidied,
                                         biomarker.excl.anti.coag$tissue.factor$tidied,
                                         biomarker.excl.anti.coag$troponin$tidied,
                                         biomarker.excl.anti.coag$bnp$tidied,
                                         biomarker.excl.anti.coag$mrproanp$tidied,
                                         biomarker.excl.anti.coag$crp$tidied,
                                         ## biomarker.excl.anti.coag$d.dimer$tidied,
                                         biomarker.excl.anti.coag$prothombin.time.cat$tidied,
                                         biomarker.excl.anti.coag$aptt.cat$tidied,
                                         biomarker.excl.anti.coag$clauss.fibrinogen.cat$tidied,
                                         biomarker.excl.anti.coag$ddimer.innovance.cat$tidied,
                                         biomarker.excl.anti.coag$ddimer.elisa.cat$tidied,
                                         ## biomarker.excl.anti.coag$thrombin.generation.lag.time.cat$tidied,
                                         biomarker.excl.anti.coag$thrombin.generation.endogenous.potential.cat$tidied,
                                         biomarker.excl.anti.coag$thrombin.generation.peak.cat$tidied,
                                         biomarker.excl.anti.coag$thrombin.generation.time.to.peak.cat$tidied,
                                         biomarker.excl.anti.coag$plasmin.antiplasmin.cat$tidied,
                                         biomarker.excl.anti.coag$prothrombin.fragments.cat$tidied,
                                         biomarker.excl.anti.coag$tissue.factor.cat$tidied,
                                         biomarker.excl.anti.coag$troponin.cat$tidied,
                                         biomarker.excl.anti.coag$bnp.cat$tidied,
                                         biomarker.excl.anti.coag$mrproanp.cat$tidied,
                                         biomarker.excl.anti.coag$crp.cat$tidied,
                                         biomarker.excl.anti.coag$d.dimer.cat$tidied,
                                         biomarker.excl.anti.coag$d.dimer.gestation.cat$tidied)
biomarker.excl.anti.coag$glance <- rbind(biomarker.excl.anti.coag$prothombin.time$glance,
                                         biomarker.excl.anti.coag$aptt$glance,
                                         biomarker.excl.anti.coag$clauss.fibrinogen$glance,
                                         biomarker.excl.anti.coag$ddimer.innovance$glance,
                                         biomarker.excl.anti.coag$ddimer.elisa$glance,
                                         biomarker.excl.anti.coag$thrombin.generation.lag.time$glance,
                                         biomarker.excl.anti.coag$thrombin.generation.endogenous.potential$glance,
                                         biomarker.excl.anti.coag$thrombin.generation.peak$glance,
                                         biomarker.excl.anti.coag$thrombin.generation.time.to.peak$glance,
                                         biomarker.excl.anti.coag$plasmin.antiplasmin$glance,
                                         biomarker.excl.anti.coag$prothrombin.fragments$glance,
                                         biomarker.excl.anti.coag$tissue.factor$glance,
                                         biomarker.excl.anti.coag$troponin$glance,
                                         biomarker.excl.anti.coag$bnp$glance,
                                         biomarker.excl.anti.coag$mrproanp$glance,
                                         biomarker.excl.anti.coag$crp$glance,
                                         ## biomarker.excl.anti.coag$d.dimer$glance,
                                         biomarker.excl.anti.coag$prothombin.time.cat$glance,
                                         biomarker.excl.anti.coag$aptt.cat$glance,
                                         biomarker.excl.anti.coag$clauss.fibrinogen.cat$glance,
                                         biomarker.excl.anti.coag$ddimer.innovance.cat$glance,
                                         biomarker.excl.anti.coag$ddimer.elisa.cat$glance,
                                         ## biomarker.excl.anti.coag$thrombin.generation.lag.time.cat$glance,
                                         biomarker.excl.anti.coag$thrombin.generation.endogenous.potential.cat$glance,
                                         biomarker.excl.anti.coag$thrombin.generation.peak.cat$glance,
                                         biomarker.excl.anti.coag$thrombin.generation.time.to.peak.cat$glance,
                                         biomarker.excl.anti.coag$plasmin.antiplasmin.cat$glance,
                                         biomarker.excl.anti.coag$prothrombin.fragments.cat$glance,
                                         biomarker.excl.anti.coag$tissue.factor.cat$glance,
                                         biomarker.excl.anti.coag$troponin.cat$glance,
                                         biomarker.excl.anti.coag$bnp.cat$glance,
                                         biomarker.excl.anti.coag$mrproanp.cat$glance,
                                         biomarker.excl.anti.coag$crp.cat$glance,
                                         biomarker.excl.anti.coag$d.dimer.cat$glance,
                                         biomarker.excl.anti.coag$d.dimer.gestation.cat$glance)
## Combine all predicted
biomarker.excl.anti.coag$predicted <- rbind(biomarker.excl.anti.coag$prothombin.time$predicted,
                                            biomarker.excl.anti.coag$aptt$predicted,
                                            biomarker.excl.anti.coag$clauss.fibrinogen$predicted,
                                            biomarker.excl.anti.coag$ddimer.innovance$predicted,
                                            biomarker.excl.anti.coag$ddimer.elisa$predicted,
                                            biomarker.excl.anti.coag$thrombin.generation.lag.time$predicted,
                                            biomarker.excl.anti.coag$thrombin.generation.endogenous.potential$predicted,
                                            biomarker.excl.anti.coag$thrombin.generation.peak$predicted,
                                            biomarker.excl.anti.coag$thrombin.generation.time.to.peak$predicted,
                                            biomarker.excl.anti.coag$plasmin.antiplasmin$predicted,
                                            biomarker.excl.anti.coag$prothrombin.fragments$predicted,
                                            biomarker.excl.anti.coag$tissue.factor$predicted,
                                            biomarker.excl.anti.coag$troponin$predicted,
                                            biomarker.excl.anti.coag$bnp$predicted,
                                            biomarker.excl.anti.coag$mrproanp$predicted,
                                            biomarker.excl.anti.coag$crp$predicted,
                                            ## biomarker.excl.anti.coag$d.dimer$predicted,
                                            biomarker.excl.anti.coag$prothombin.time.cat$predicted,
                                            biomarker.excl.anti.coag$aptt.cat$predicted,
                                            biomarker.excl.anti.coag$clauss.fibrinogen.cat$predicted,
                                            biomarker.excl.anti.coag$ddimer.innovance.cat$predicted,
                                            biomarker.excl.anti.coag$ddimer.elisa.cat$predicted,
                                            ## biomarker.excl.anti.coag$thrombin.generation.lag.time.cat$predicted,
                                            biomarker.excl.anti.coag$thrombin.generation.endogenous.potential.cat$predicted,
                                            biomarker.excl.anti.coag$thrombin.generation.peak.cat$predicted,
                                            biomarker.excl.anti.coag$thrombin.generation.time.to.peak.cat$predicted,
                                            biomarker.excl.anti.coag$plasmin.antiplasmin.cat$predicted,
                                            biomarker.excl.anti.coag$prothrombin.fragments.cat$predicted,
                                            biomarker.excl.anti.coag$tissue.factor.cat$predicted,
                                            biomarker.excl.anti.coag$troponin.cat$predicted,
                                            biomarker.excl.anti.coag$bnp.cat$predicted,
                                            biomarker.excl.anti.coag$mrproanp.cat$predicted,
                                            biomarker.excl.anti.coag$crp.cat$predicted,
                                            biomarker.excl.anti.coag$d.dimer.cat$predicted,
                                            biomarker.excl.anti.coag$d.dimer.gestation.cat$predicted)
## Combine all tabulations
## biomarker.excl.anti.coag$cross.tab <- rbind(biomarker.excl.anti.coag$prothombin.time$table,
##                                  biomarker.excl.anti.coag$aptt$table,
##                                  biomarker.excl.anti.coag$clauss.fibrinogen$table,
##                                  biomarker.excl.anti.coag$ddimer.innovance$table,
##                                  biomarker.excl.anti.coag$ddimer.elisa$table,
##                                  biomarker.excl.anti.coag$thrombin.generation.lag.time$table,
##                                  biomarker.excl.anti.coag$thrombin.generation.endogenous.potential$table,
##                                  biomarker.excl.anti.coag$thrombin.generation.peak$table,
##                                  biomarker.excl.anti.coag$thrombin.generation.time.to.peak$table,
##                                  biomarker.excl.anti.coag$plasmin.antiplasmin$table,
##                                  biomarker.excl.anti.coag$prothrombin.fragments$table,
##                                  biomarker.excl.anti.coag$tissue.factor$table,
##                                  biomarker.excl.anti.coag$troponin$table,
##                                  biomarker.excl.anti.coag$bnp$table,
##                                  biomarker.excl.anti.coag$mrproanp$table,
##                                  biomarker.excl.anti.coag$crp$table,
##                                  ## biomarker.excl.anti.coag$d.dimer$table,
##                                  biomarker.excl.anti.coag$prothombin.time.cat$table,
##                                  biomarker.excl.anti.coag$aptt.cat$table,
##                                  biomarker.excl.anti.coag$clauss.fibrinogen.cat$table,
##                                  biomarker.excl.anti.coag$ddimer.innovance.cat$table,
##                                  biomarker.excl.anti.coag$ddimer.elisa.cat$table,
##                                  ## biomarker.excl.anti.coag$thrombin.generation.lag.time.cat$table,
##                                  biomarker.excl.anti.coag$thrombin.generation.endogenous.potential.cat$table,
##                                  biomarker.excl.anti.coag$thrombin.generation.peak.cat$table,
##                                  biomarker.excl.anti.coag$thrombin.generation.time.to.peak.cat$table,
##                                  biomarker.excl.anti.coag$plasmin.antiplasmin.cat$table,
##                                  biomarker.excl.anti.coag$prothrombin.fragments.cat$table,
##                                  biomarker.excl.anti.coag$tissue.factor.cat$table,
##                                  biomarker.excl.anti.coag$troponin.cat$table,
##                                  biomarker.excl.anti.coag$bnp.cat$table,
##                                  biomarker.excl.anti.coag$mrproanp.cat$table,
##                                  biomarker.excl.anti.coag$crp.cat$table,
##                                  biomarker.excl.anti.coag$d.dimer.cat$table,
##                                  biomarker.excl.anti.coag$d.dimer.gestation.cat$table)

## Extract the data used from each overall binary dichotomisation and bind into one
## for summarisation using dipep_roc(), required since the $predicted for each
## model has probabilities and dipep_roc() takes these and uses a supplied
## threshold derives sensitivity and specificity
biomarker.excl.anti.coag$aptt.cat$fitted$data                              <- dipep_extract_binary(df      = biomarker.excl.anti.coag$aptt.cat$fitted$data,
                                                                                                   outcome = 'aptt.cat')
biomarker.excl.anti.coag$clauss.fibrinogen.cat$fitted$data                        <- dipep_extract_binary(df      = biomarker.excl.anti.coag$clauss.fibrinogen.cat$fitted$data,
                                                                                                   outcome = 'clauss.fibrinogen.cat')
biomarker.excl.anti.coag$ddimer.innovance.cat$fitted$data                         <- dipep_extract_binary(df      = biomarker.excl.anti.coag$ddimer.innovance.cat$fitted$data,
                                                                                                   outcome = 'ddimer.innovance.cat')
biomarker.excl.anti.coag$ddimer.elisa.cat$fitted$data                             <- dipep_extract_binary(df      = biomarker.excl.anti.coag$ddimer.elisa.cat$fitted$data,
                                                                                                   outcome = 'ddimer.elisa.cat')
biomarker.excl.anti.coag$thrombin.generation.endogenous.potential.cat$fitted$data <- dipep_extract_binary(df      = biomarker.excl.anti.coag$thrombin.generation.endogenous.potential.cat$fitted$data,
                                                                                                   outcome = 'thrombin.generation.endogenous.potential.cat')
biomarker.excl.anti.coag$thrombin.generation.peak.cat$fitted$data                 <- dipep_extract_binary(df      = biomarker.excl.anti.coag$thrombin.generation.peak.cat$fitted$data,
                                                                                                   outcome = 'thrombin.generation.peak.cat')
biomarker.excl.anti.coag$thrombin.generation.time.to.peak.cat$fitted$data         <- dipep_extract_binary(df      = biomarker.excl.anti.coag$thrombin.generation.time.to.peak.cat$fitted$data,
                                                                                                   outcome = 'thrombin.generation.time.to.peak.cat')
biomarker.excl.anti.coag$plasmin.antiplasmin.cat$fitted$data                      <- dipep_extract_binary(df      = biomarker.excl.anti.coag$plasmin.antiplasmin.cat$fitted$data,
                                                                                                   outcome = 'plasmin.antiplasmin.cat')
biomarker.excl.anti.coag$prothrombin.fragments.cat$fitted$data                    <- dipep_extract_binary(df      = biomarker.excl.anti.coag$prothrombin.fragments.cat$fitted$data,
                                                                                                   outcome = 'prothrombin.fragments.cat')
biomarker.excl.anti.coag$tissue.factor.cat$fitted$data                            <- dipep_extract_binary(df      = biomarker.excl.anti.coag$tissue.factor.cat$fitted$data,
                                                                                                   outcome = 'tissue.factor.cat')
biomarker.excl.anti.coag$troponin.cat$fitted$data                                 <- dipep_extract_binary(df      = biomarker.excl.anti.coag$troponin.cat$fitted$data,
                                                                                                   outcome = 'troponin.cat')
biomarker.excl.anti.coag$bnp.cat$fitted$data                                      <- dipep_extract_binary(df      = biomarker.excl.anti.coag$bnp.cat$fitted$data,
                                                                                                   outcome = 'bnp.cat')
biomarker.excl.anti.coag$mrproanp.cat$fitted$data                                 <- dipep_extract_binary(df      = biomarker.excl.anti.coag$mrproanp.cat$fitted$data,
                                                                                                   outcome = 'mrproanp.cat')
biomarker.excl.anti.coag$d.dimer.cat$fitted$data                                  <- dipep_extract_binary(df      = biomarker.excl.anti.coag$d.dimer.cat$fitted$data,
                                                                                                          outcome = 'd.dimer.cat')
biomarker.excl.anti.coag$d.dimer.gestation.cat$fitted$data                        <- dipep_extract_binary(df      = biomarker.excl.anti.coag$d.dimer.gestation.cat$fitted$data,
                                                                                                          outcome = 'd.dimer.gestation.cat')
biomarker.excl.anti.coag$crp.cat$fitted$data                                      <- dipep_extract_binary(df      = biomarker.excl.anti.coag$crp.cat$fitted$data,
                                                                                                   outcome = 'crp.cat')
biomarker.excl.anti.coag$predicted.existing <- rbind(biomarker.excl.anti.coag$aptt.cat$fitted$data,
                                                     biomarker.excl.anti.coag$clauss.fibrinogen.cat$fitted$data,
                                                     biomarker.excl.anti.coag$ddimer.innovance.cat$fitted$data,
                                                     biomarker.excl.anti.coag$ddimer.elisa.cat$fitted$data,
                                                     biomarker.excl.anti.coag$thrombin.generation.endogenous.potential.cat$fitted$data,
                                                     biomarker.excl.anti.coag$thrombin.generation.peak.cat$fitted$data,
                                                     biomarker.excl.anti.coag$thrombin.generation.time.to.peak.cat$fitted$data,
                                                     biomarker.excl.anti.coag$plasmin.antiplasmin.cat$fitted$data,
                                                     biomarker.excl.anti.coag$prothrombin.fragments.cat$fitted$data,
                                                     biomarker.excl.anti.coag$tissue.factor.cat$fitted$data,
                                                     biomarker.excl.anti.coag$troponin.cat$fitted$data,
                                                     biomarker.excl.anti.coag$bnp.cat$fitted$data,
                                                     biomarker.excl.anti.coag$mrproanp.cat$fitted$data,
                                                     biomarker.excl.anti.coag$d.dimer.cat$fitted$data,
                                                     biomarker.excl.anti.coag$d.dimer.gestation.cat$fitted$data,
                                                     biomarker.excl.anti.coag$crp.cat$fitted$data) %>%
                               mutate(D = first.st.vte,
                                      M = case_when(.$predictor == 'Normal' ~ 0,
                                                    .$predictor == 'Abnormal'    ~ 1),
                                      term = case_when(.$name == 'aptt.cat' ~ 'APTT : Dichotomised',
                                                       .$name == 'clauss.fibrinogen.cat' ~ 'Clauss Fibrinogen : Dichotomised',
                                                       .$name == 'ddimer.innovance.cat' ~ 'D-Dimer (Innovance) : Dichotomised',
                                                       .$name == 'ddimer.elisa.cat' ~ 'D-Dimer (ELISA) : Dichotomised',
                                                       .$name == 'thrombin.generation.lag.time.cat' ~ 'Thrombin Generation (Lag Time) : Dichotomised',
                                                       .$name == 'thrombin.generation.endogenous.potential.cat' ~ 'Thrombin Generation (Endogenous Potential) : Dichotomised',
                                                       .$name == 'thrombin.generation.peak.cat' ~ 'Thrombin Generation (Peak) : Dichotomised',
                                                       .$name == 'thrombin.generation.time.to.peak.cat' ~ 'Thrombin Generation (Time to Peak) : Dichotomised',
                                                       .$name == 'plasmin.antiplasmin.cat' ~ 'Plasmin-antiplasmin : Dichotomised',
                                                       .$name == 'prothrombin.fragments.cat' ~ 'Prothombin (Time) : Dichotomised',
                                                       .$name == 'tissue.factor.cat' ~ 'Tissue Factor : Dichotomised',
                                                       .$name == 'troponin.cat' ~ 'Troponin : Dichotomised',
                                                       .$name == 'bnp.cat' ~ 'BNP : Dichotomised',
                                                       .$name == 'mrproanp.cat' ~ 'MRproANP : Dichotomised',
                                                       .$name == 'd.dimer.cat' ~ 'D-Dimer (Hospital) : Dichotomised',
                                                       .$name == 'd.dimer.gestation.cat' ~ 'D-Dimer (Hospital) : Dichotomised (Gestation Specific)',
                                                       .$name == 'crp.cat' ~ 'C-Reactive Protein : Dichotomised')) %>%
                              dplyr::select(D, predictor, M, name, term)

```
