Detailed description of the proposed analyses were formulated and signed-off in the Statistical Analysis Plan (SAP) as prescribed by the CTRUs *ST001 - The Statistical Analysis Plan* Standard Operating Procedure (SOP), this document can be viewed [online](https://www.overleaf.com/read/rdyrzjmxxghz).  The methods described below are for the most part lifted directly from the SAP but have where necessary been modified to reflect what has actually been requested and performed as the analyses progressed.

### Data Sources

The [UK Obstetric Surveillance System (UKOSS)](https://www.npeu.ox.ac.uk/ukoss/methodology) is a UK-wide surveillance system established to conduct research on uncommon disorders of pregnancy.  This resource will be used to identify cases retrospectively from across the UK and data on these individuals will be extracted by UKOSS in Oxford and shared with CTRU Data Management where it will be stored in a local database.  Controls will be identified through a prospective study of pregnant or postpartum women presenting to eight hospitals (see table~\ref{participating-hospitals}) with suspected PE, of whom it is anticipated 98\% will have no PE diagnosis, any who do will be analysed as cases.  Blood samples from a further 20 women diagnosed at the same hospitals with [deep vein thrombosis (DVT)](http://en.wikipedia.org/wiki/Deep\_vein\_thrombosis) will be taken to determine whether the blood tests can accurately identify clots (DVT is often a precursor to PE.).

Hospital														| Contact
--------------------------------------------------------------	|--------------------------------------------------------------------------
Barts Health NHS Trust											| [Prof Tim Harris](mailto:Tim.Harris@bartshealth.nhs.uk)
Bolton															| [Dr Richard Parris](mailto:richard.parris@boltonft.nhs.uk)
Bradford														| [Prof Derek Tuffnell](mailto:derek.tuffnell@bthft.nhs.uk)
Guy's and St Thomas' NHS Foundation Trust						| [Dr Catherine Nelson-Piercy](mailto:catherine.nelson-piercy@gstt.nhs.uk)
Hull and East Yorkshire Hospitals NHS Trust						| [Dr William Townend](mailto:William.Townend@hey.nhs.uk)
Leeds Teaching Hospitals NHS Trust								| [Dr Etienne Ciantar](mailto:E.Ciantar@leeds.ac.uk)
Nottingham University Hospitals NHS Trust						| [Dr Gillian Swallow](mailto:Gillian.Swallow@nuh.nhs.uk)
Portsmouth Hospitals NHS Trust									| [Dr Chris Vorwerk](mailto:Chris.Vorwerk@porthosp.nhs.uk)
Royal Berkshire NHS Foundation Trust							| [Dr Andrew Walden](mailto:andrew.walden@nhs.net)
Central Manchester University Hospitals NHS Foundation Trust	| [Dr Rick Body](mailto:richard.body@manchester.ac.uk)
Sheffield														| [Prof Steve Goodacre](mailto:s.goodacre@sheffield.ac.uk)

### Inclusion/Exclusion Criteria

#### Inclusion Criteria - Diagnosed PE}

* PE confirmed using imaging (angiography, CT, magnetic resonance imaging or ventilation-perfusion scan showing a high probability of PE).
* PE confirmed at surgery or post-mortem.
* A clinical diagnosis of PE who received a course of anticoagulation therapy for more than one week.

#### Exclusion Criteria - Diagnosed PE

* Women with PE identified on asymptomatic screening.


#### Inclusion Criteria - Suspected PE

* Any pregnant or postpartum woman who requires diagnostic imaging for suspected PE (as outlined above, but also including lower venous imaging) will be eligible for inclusion.

#### Exclusion Criteria - Suspected PE

* Women who need life support upon presentation to hospital (including chest compressions and assisted ventilation)
* Women who have been diagnosed with PE earlier in the current pregnancy and are currently receiving treatment
* Women who are unable or unwilling to provide informed consent.
* Women $< 16$ years of age.

#### Non-recruited Suspected PE

As we recognise the difficulty in recruiting in an emergency setting, we will collect baseline non-identifiable data from the case notes of those women who were eligible but were not asked to participate in the study.

#### Analysis Populations

The primary analysis population will consist of women from both cohorts who presented with suspected PE and had PE either diagnosed or ruled out by diagnostic imaging, surgery or post mortem.  Women with diagnosed PE who did not present with suspected PE prior to diagnosis, including those who needed life support upon presentation to hospital (chest compression's and ventilator support) will be excluded from primary and secondary analyses, but their data used to estimate key parameters, such as incidence of PE in pregnancy and postpartum.  Women with a clinical diagnosis of PE based on imaging evidence of DVT will be analysed as cases.  Women with a purely clinical diagnosis of PE (i.e. without any imaging or pathological evidence of DVT or PE) will be excluded from primary analysis but included as having PE in secondary analysis. Women who have PE ruled out without imaging (e.g. if imaging is declined, cannot be performed or if an initial decision that imaging was required is overruled) will be excluded from primary analysis but included as having no PE in secondary analysis.  The study is non-interventional so no Intention To Treat (ITT) or Per-Protocol (PP) subpopulations require analysing.

### Events

Data is collected at certain 'events' and will be summarised according to these.

Event             | Description
------------------|------------------------
Baseline          | Initial presentation with symptoms
30-day follow-up  | Questionnaires administered and collected 30-days after baseline
Thrombotic Events | Details of thrombotic events that have occurred (variable time from baseline)

### Classification of participants as having PE or no PE

Two independent assessors, blind to clinical predictors and blood results, will classify participants as having PE or no PE using diagnostic imaging results, details of adverse events and details of treatments given. Disagreements will be resolved through adjudication by a third assessor. Non-identifiable data from women with suspected PE who were not recruited will be assessed in the same way and classified as PE or no PE.

### Demographics and Baseline Characteristics

The number of individuals with and without PE will be calculated and their baseline demographics detailing the age, week of pregnancy and previous partums along with all predictor variables at baseline via mean, standard deviation (SD), range, median and inter-quartile range (IQR).  The demographics, baseline characteristics and rate of PE diagnosis will be compared between the recruited and non-recruited women with suspected PE (primary analysis limited to those with imaging, secondary including all women) to determine whether those recruited with suspected PE are a representative cohort.

### Missing and Spurious Data

There will be no missing data for the reference standard because all women will be classified as having or not having PE based on the available data.  However, for the predictor variables there is scope for missing data if the attending clinician fails to measure or record the data.  This is most likely to happen when the variable is anticipated to be or recorded as negative or normal, and thus unlikely to change clinical care.  To address this missing values will be imputed based on clinically determined "normal" values defined by [Prof Steve Goodacre](mailto:s.goodacre@sheffield.ac.uk) and [Dr Gordon Fuller](mailto:g.fuller@sheffield.ac.uk).  Sensitivity will be assessed by comparing these results to complete cases.  Multiple imputation was to be investigated it is not advisable as it has been demonstrated to perform poorly for recurrsive partitioning(@hapfelmeier2012) and can lead to biased point estimates and are inefficient compared to other methods (@sullivan2016).  There are parctical issues to performing analysis of multiply-imputed datasets via recursive partitioning and LASSO (i.e. the statistician doesn't know how to do this).

#### Withdrawals

Where patients have withdrawn from the study their data will be included upto the point of withdrawal unless they have explicitly requested to have all of their data withdrawn from the study

### Questionnaire Data

Summaries of responses to assessment questionnaires will be made in tabular form for each time point.

### Biomarkers

The blood biomarkers that are to be assayed and analysed for their predictive value in this study.  These are assayed by UKOSS and the data forwarded to the CTRU.


### Modelling

Two approaches are to be taken to deriving a model to predict Pulmonary Embolisms in pregnant women, [recrusive partitioning](https://en.wikipedia.org/wiki/Recursive_partitioning) implemented in the [`rpart`](https://cran.r-project.org/package=rpart) package and [LASSO regression](https://en.wikipedia.org/wiki/Lasso_(statistics)) (@friedman2010) implemented in the [`glmnet`](https://cran.r-project.org/package=glmnet) package.  Both require the inclusion of putative risk factors that are thought to be of some predictive value and will then attempt to derive a minimal subset of variables that maximises the predictive value.  Models are then validated by [leave one out cross-validation]()

#### LASSO

The implementation of the LASSO model that is being used is implemented in the R package [`glmnet`](https://cran.r-project.org/package=glmnet) which uses ridge and LASSO penatlities simultaneously.  Fitting models using this approach is controlled by two parameters, $\alpha$ which when set to 1 uses pure LASSO penalty and when 0 uses pure ridge-regression penalties and $\lambda$ which is the overall penalisation to be used.

#### Recursive Partitioning


#### Risk Variables
Risk variables are detailed in the following table, many of the continuous variables where the risk is non-linear are to be categorised, despite the reduction in prognostic accuracy this results in (@steyerberg2001) and the rules for doing so are shown in table below.

Variable Description                    			| Boundry              | Classification/Risk | Data
----------------------------------------------------|----------------------|---------------------|--------------
Age													| $\le 35$             | 0                   | `age`
Age													| $>35$                | 1                   | `age`
BMI													| $< 30$               | 0                   | `bmi`
BMI													| $\ge 30$             | 1                   | `bmi`
Smoking												| Not Current Smoker   | 0                   | `smoking`
Smoking												| Current Smoker       | 1                   | `smoking`
Previous Pregnancy									| None                 | 0                   | `pregnancies.over`
Previous Pregnancy									| Any                  | 1                   | `pregnancies.over`
Previous Pregnancy Problems							| None                 | 0                   | `prev.preg.problem`
Previous Pregnancy Problems							| Any                  | 1                   | `prev.preg.problem`
History of thombosis in $1^o$ relatives				| None                 | 0                   | `history.thrombosis`
History of thombosis in $1^o$ relatives				| None                 | 1                   | `history.thrombosis`
History of Varicose Veins							| None                 | 0                   | `history.veins`
History of Varicose Veins							| Any                  | 1                   | `history.veins`
History of Intravenous drug use						| None                 | 0                   | `history.iv.drugs`
History of Intravenous drug use						| Any                  | 1                   | `history.iv.drugs`
History of thrombophilia							| None                 | 0                   | `thrombo`
History of thrombophilia							| Any                  | 1                   | `thrombo`
Surgery in last 4 weeks								| None                 | 0                   | `surgery`
Surgery in last 4 weeks								| Any                  | 1                   | `surgery`
Significant Injury in last 4 weeks                  | None                 | 0                   | `injury`
Significant Injury in last 4 weeks                  | Any                  | 1                   | `injury`
Past History of Thrombosis							| None                 | 0                   | `thrombosis`
Past History of Thrombosis							| Any                  | 1                   | `thrombosis`
Other Previous/Pre-existing Medical Problems        | None                 | 0                   | `medical.probs`
Other Previous/Pre-existing Medical Problems        | Any                  | 1                   | `medical.probs`
Pre or Post Partum									| Prepartum (i.e. pregnant)| 0               | `preg.post`
Pre or Post Partum									| Postpartum               | 1               | `preg.post`
Trimester											| $1^{st}$ or $2^{nd}$     | 0               | `trimester` (`edd`)
Trimester											| $3^{rd}$                 | 1               | `trimester` (`edd`)
Trimester											| Post-partum              | 1               | `trimester` (`edd`)
Multiple Pregnancy									| None                 | 0                   | `multiple.preg`
Multiple Pregnancy									| Any (i.e. $\ge 2$)   | 1                   | `multiple.preg`
Long haul Travel during Pregnancy                   | None                 | 0                   | `travel`
Long haul Travel during Pregnancy                   | Any                  | 1                   | `travel`
Period of Immobility/Bed Rest during pregnancy      | None                 | 0                   | `immobil`
Period of Immobility/Bed Rest during pregnancy      | Any                  | 1                   | `immobil`
Prior Thrombotic Event								| None                 | 0                   | `thromb_event`
Prior Thrombotic Event								| Any                  | 1                   | `thromb_event`
Pleuritic Chest Pain								| None                 | 0                   | `?`
Pleuritic Chest Pain								| Any                  | 1                   | `?`
Other (non-Pleuritic) Chest Pain                    | None                 | 0                   | `?`
Other (non-Pleuritic) Chest Pain                    | Any                  | 1                   | `?`
Shortness of Breath on Exertion                     | None                 | 0                   | `?`
Shortness of Breath on Exertion                     | Any                  | 1                   | `?`
Shortness of Breath at Rest							| None                 | 0                   | `?`
Shortness of Breath at Rest							| Any                  | 1                   | `?`
Haemoptysis											| None                 | 0                   | `?`
Haemoptysis											| Any                  | 1                   | `?`
Other Productive Cough								| None                 | 0                   | `?`
Other Productive Cough								| Any                  | 1                   | `?`
Syncope												| None                 | 0                   | `?`
Syncope												| Any                  | 1                   | `?`
Palpitations										| None                 | 0                   | `?`
Palpitations										| Any                  | 1                   | `?`
Other Symptoms										| None                 | 0                   | `?`
Other Symptoms										| Any                  | 1                   | `?`
Clinical Signs of Deep Vein Thrombosis              | None                 | 0                   | `?`
Clinical Signs of Deep Vein Thrombosis              | Any                  | 1                   | `?`
Pulmonary Embolism related ECG abnormality          | None                 | 0                   | `ecg`
Pulmonary Embolism related ECG abnormality          | Any                  | 1                   | `ecg`
Pulmonary Embolism related CXR abnormality          | None                 | 0                   | `xray`  (`xray.specify`)
Pulmonary Embolism related CXR abnormality          | Any                  | 1                   | `xray` (`xray.specify`)
CXR shows alternative diagnosis                     | None                 | 0                   | `xray`  (`xray.specify`)
CXR shows alternative diagnosis                     | Any                  | 1                   | `xray`  (`xray.specify`)
Likely Diagnosis									| Not Pulmonary Embolism | 0                   | `?`
Likely Diagnosis									| Pulmonary Embolism     | 1                   | `?`
D-Dimer												| Normal Range           | 0                   | `?`
D-Dimer												| Exceeds Normal Range   | 1                   | `?`
D-Dimer                                         | More than double the upper normal range | 2      | `?`
Heart Rate										| $\le 100$ ($1^{st}$ or $2^{nd}$ trimester or postpartum) | 0                   | `heart.rate`
Heart Rate										| $\le 110$ ($3^{rd}$ trimester)                           | 0                   | `heart.rate`
Heart Rate										| $> 100$ ($1^{st}$ or $2^{nd}$ trimester or postpartum)   | 1                   | `heart.rate`
Heart Rate										| $> 110$ ($3^{rd}$ trimester)                             | 1                   | `heart.rate`
Respiratory Rate 								| $\le 24$                                                 | 0                   | `respiratory.rate`
Respiratory Rate (Tachypnea)                    | $> 24$                                                   | 1                   | `respiratory.rate`
Oxygen Saturation								| $\ge 94$                                                 | 0                   | `o2.saturation`
Oxygen Saturation								| $< 94$                                                   | 1                   | `o2.saturation`
Systolic Blood Pressure							| $\ge 90$                                                 | 0                   | `bp.systolic`
Systolic Blood Pressure							| $< 90$                                                   | 1                   | `bp.systolic`
Diastolic Blood Pressure						| $\ge 60$                                                 | 0                   | `bp.diastolic`
Diastolic Blood Pressure						| $< 60$                                                   | 1                   | `bp.diastolic`
Temperature										| $\le 37.4$                                               | 0                   | `temperature`
Temperature										| $> 37.4$                                                 | 1                   | `temperature`
D-Dimers (ELISA)								| $\le  400$| 0                   | `d.dimer.cat`
D-Dimers (ELISA)								| $>    400$| 1                   | `d.dimer.cat`
D-Dimers (latex agglutination)					| $\le 1.13$| 0                   | `?`
D-Dimers (latex agglutination)					| $>   1.13$| 1                   | `?`
Plasmin-antiplasmin Assay (PAP)					| $\le  800$| 0                   | `plasmin.antiplasmin.cat`
Plasmin-antiplasmin Assay (PAP)					| $>    800$| 1                   | `plasmin.antiplasmin.cat`
Prothombin Fragmen 1+2 (PF 1+2)					| $\le 1200$| 0                   | `prothrombin.fragments.cat`
Prothombin Fragmen 1+2 (PF 1+2)					| $>   1200$| 1                   | `prothrombin.fragments.cat`
Thrombin Generation (Lag Time)  				| $\le 3.4$ | 0                   | `thrombin.generation.lag.time.cat`
Thrombin Generation	(Lag Time)					| $>   3.4$ | 1                   | `thrombin.generation.lag.time.cat`
Thrombin Generation	(Peak)						| $\le 475$   | 0                   | `thrombin.generation.peak.cat`
Thrombin Generation	(Peak)						| $>   475$ | 1                   | `thrombin.generation.peak.cat`
Thrombin Generation	(Time to Peak)				| $\le 7.7$ | 0                   | `thrombin.generation.time.to.peak.cat`
Thrombin Generation	(Time to Peak)				| $>   7.7$ | 1                   | `thrombin.generation.time.to.peak.cat`
Thrombin Generation	(Endogenous Potential)		| $\le 1533$| 0                   | `thrombin.generation.endogenous.potential.cat`
Thrombin Generation	(Endogenous Potential)		| $>   1533$| 1                   | `thrombin.generation.endogenous.potential.cat`
Prothombin Time (PT)							| $\le 15.9$| 0                   | `prothombin.time.cat`
Prothombin Time (PT)							| $>   15.9$| 1                   | `prothombin.time.cat`
Activated Partial Thromboplastin Time (APTT)	| $\le 52$  | 0                   | `aptt.cat`
Activated Partial Thromboplastin Time (APTT)    | $>   52$  | 1                   | `aptt.cat`
Clauss Fibrinogen								| $\le 4.11$| 0                   | `clauss.fibrinogen.cat`
Clauss Fibrinogen								| $>   4.11$| 1                   | `clauss.fibrinogen.cat`
Soluble Tissue Factor (sTF)						| $\le 300$ | 0                   | `tissue.factor.cat`
Soluble Tissue Factor (sTF)						| $>   300$ | 1                   | `tissue.factor.cat`
Troponin I										| $\le 2.63$| 0                   | `troponin.cat`
Troponin I										| $>   2.63$| 1                   | `troponin.cat`
B-Type Natriuretic Peptide						| $\le 523$ | 0                   | `bnp.cat`
B-Type Natriuretic Peptide						| $>   523$ | 1                   | `bnp.cat`
C-Reactive Protein      						| $\le 3104$| 0                   | `crp.cat`
C-Reactive Protein	        					| $>   3104$| 1                   | `crp.cat`
MRproAMP                						| $\le 954$ | 0                   | `mrproanp.cat`
MRproAMP	                					| $>   954$ | 1                   | `mrproanp.cat`

### Model Assessment

#### Sensitivity and Specificity

[Sensitivity and specificity](http://en.wikipedia.org/wiki/Sensitivity\_and\_specificity) are properties that arise when trying to classify 'things' (in this case individuals with PE).  There are four ways in which individuals can be classified with respect to their predicted and true classification of PE and these are shown in the table below.

Prediction  | True PE Positive                    | True PE Negative
------------|-------------------------------------|-----------------------------------
PE Positive | True Positive (TP)                  | False Positive (FP) (Type I Error)
PE Negative | False Negative (FN) (Type II Error) | True Negative (TN)


The sensitivity (or True Positive Rate) is defined as...

$$
 TPR = \frac{TP}{TP + FN}
$$

...whilst the specificity (or True Negative Rate) is defined as...

$$
 TNR = \frac{TN}{FP + TN}
$$

Assessing the combined sensitivity and specificity of each method of classification will be performed by plotting [Receiver Operating Characteristic (ROC) curves](https://en.wikipedia.org/wiki/Receiver_operating_characteristic) and quantified by the [Area Under the Curve (AUC)](https://en.wikipedia.org/wiki/Receiver_operating_characteristic#Area_under_the_curve).  For an illustrative example of applying ROC and AUC and some criticisms see the article [Illustrated Guide to ROC and AUC](https://www.r-bloggers.com/illustrated-guide-to-roc-and-auc/).  Fordetailed information on plotting ROC curves in R using [ggplot2](http://docs.ggplot2.org/current/) see the [plotROC vignette](https://sachsmc.github.io/plotROC/)

#### Positive & Negative Predictive Value

Related to the sensitivity and specificity the [positive and negative predictive value](https://en.wikipedia.org/wiki/Positive\_and\_negative\_predictive\_values) (PPV and NPV respectively) are the proportions of positive and negative predictions that are correct.

$$
PPV = \frac{TP}{TP + FP}
$$

$$
NPV = \frac{TN}{TN + FN}
$$

#### Possible Alternatives

I recently came across a paper discussing alternatives to Area Under the ROC curve (@pencina2008) and proposes two new measures which offer improvements, one based on both the sensitivity and specificity, the other based on reclassification tables.  The approach has been implemented in the `Hmisc` package for R (see [comment from packages author on R-help](http://r.789695.n4.nabble.com/Calculating-Sensitivity-Specificity-and-Agreement-from-Logistics-Regression-Model-td874453.html)) and if the limited time available permits these will be investigated.


### Existing Rules {.tabset .tabset-fade .tabset-pills}

The simplified revised Geneva score (@klok2008), Wells Score (@wells2001) and PERC score (@kline2004) are to be assessed and compared to the derived models.  The criteria and scoring for each of these rules are described below.

#### Simplified Revised Geneva Score

Criteria             | Score        | Based on...  | Derived Variable
---------------------|--------------|--------------|--------------------
$> 65$ years old     | `1`          | `age`        | `simplified.age`
Previous DVT or PE   | `1`          | `dvt`        | `simplified.previous`
Surgery or fracture $< 1$ month | `1`          | `surgery.other`           | `simplified.surgery`
Active Malignancy $< 1$ year    | `1`          | `x`           | `simplified.neoplasm`
Unilateral lower-limb pain      | `1`          | `x`           | `simplified.lower.limb.unilateral.pain`
Haemoptysis          | `1`          | `presenting.features.haemoptysis` | `simplified.haemoptysis`
$> 75$ beats/minute  | `1`          | `heart.rate` | `simplified.heart.rate`
Lower Limb Pain      | `

An online calculator is available at [MDCalc - Geneva Score (Revised) for Pulmonary Embolism](http://www.mdcalc.com/geneva-score-revised-pulmonary-embolism/).

#### Wells Score

The patients characteristics are scored based on the following criteria...

Criteria             | Score        | Based on...  | Derived Variable
---------------------|--------------|--------------|--------------------
DVT                  | `3`   | `dvt` | `wells.dvt`
Alternative diagnosis less likely | `3` | `post.pe` | `wells.alternative`
$> 100$ beats/minute | `1.5`   | `dvt` | `wells.dvt`
Surgery/Immobile     | `1.5` | `surgery` / `immobile` | `wells.surgery.immobil`
Previous DVT or PE   | `1.5` | `dvt` / `x` | `wells.previous.dvt.pe`
Hemoptysis           | `1` | `presenting.features.haemoptysis` | `perc.haemoptysis`
Neoplasm             | `1` | `medical.other` / `medical.specify` | `perc.neoplasm`

An online calculator is available at [MDCalc - Wells Criteria for Pulmonary Embolism](http://www.mdcalc.com/wells-criteria-pulmonary-embolism-pe/).

#### PERC Score

The patients characteristics are scored based on the following criteria...

Criteria             | Score        | Based on...  | Derived Variable
---------------------|--------------|--------------|--------------------
$> 50$ years old     | `1`          | `age`        | `perc.age`
$> 100$ beats/minute | `1`          | `heart.rate` | `perc.heart.rate`
Cough                | `1`          | `presenting.features.cough`       | `perc.cough`
Haemoptysis          | `1`          | `presenting.features.haemoptysis` | `perc.haemoptysis`
Leg Swelling         | `1`          | ``other.symptoms.specify`         | `perc.leg.swelling`
DVT                  | `1`          | `dvt`        | `perc.dvt`

Scores are then classified as `High`, `Moderate` or `Low` based on the cut-points...

Score | PERC Risk of PE
------|------------------
$>6$  | `High`
$2-6$ | `Moderate`
$<2$  | `Low`

An online calculator is available at [MDCalc - PERC Rule for Pulmonary Embolism](http://www.mdcalc.com/perc-rule-pulmonary-embolism/).
