```{r child = 'subsections/recruitment.Rmd', eval = TRUE}
```

```{r child = 'subsections/missing_data.Rmd', eval = TRUE}
```

```{r child = 'subsections/demographics.Rmd', eval = TRUE}
```

```{r child = 'subsections/classification.Rmd', eval = TRUE}
```

```{r child = 'subsections/results_existing.Rmd', eval = TRUE}
```

```{r child = 'subsections/results_clinical_opinion.Rmd', eval = FALSE}
```

```{r child = 'subsections/results_biomarkers.Rmd', eval = TRUE}
```

```{r covariates, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
classification <- 'first.st'
common <- c('pregnancies.over',
            'pregnancies.under',
            ## 'history.thrombosis',
            ## 'history.iv.drug',
            'history.veins',
            ## 'travel',
            ## 'multiple.preg',
            'prev.preg.problem',
            'presenting.features.pleuritic',
            'presenting.features.non.pleuritic',
            ## 'presenting.features.sob.exertion',
            'presenting.features.sob.rest',
            'presenting.features.haemoptysis',
            'presenting.features.cough',
            'presenting.features.syncope',
            'presenting.features.palpitations',
            'presenting.features.other',
            'surgery',
            'cesarean',
            'thromb.event',
            ## 'thromboprophylaxis',
            ## 'smoking',
            'thrombosis',
            'preg.post',
            'multiple.preg',
            'ecg.pe',
            'xray.pe')
categorical <- c('age.cat',
                 'bmi.cat',
                 'temperature.cat',
                 'bp.diastolic.cat',
                 'bp.systolic.cat',
                 'o2.saturation.cat',
                 'respiratory.rate.cat',
                 'heart.rate.cat')
continuous  <- c('age',
                 'bmi',
                 'temperature',
                 'bp.diastolic',
                 'bp.systolic',
                 'o2.saturation',
                 'respiratory.rate',
                 'heart.rate')

```

```{r child = 'subsections/results_rpart.Rmd', eval = TRUE}
```

```{r child = 'subsections/results_lasso.Rmd', eval = TRUE}
```

```{r child = 'subsections/results_logistic.Rmd', eval = TRUE}
```
