> ADD TABLE(S) HERE WITH COLUMNS FOR WOMEN WITH PE AND WOMEN WITHOUT, AND ROWS FOR AGE>35, BMI≥30, SMOKING STATUS, PREVIOUS PREGNANCIES, ANY PREVIOUS PREGNANCY PROBLEMS (YES/NO), THE 7 ITEMS UNDER PREVIOUS MEDICAL HISTORY, ANY OTHER PREVIOUS MEDICAL PROBLEM, EACH TRIMSTER AND POST PARTUM, MULTIPLE PREGNANCY, LONG HAUL TRAVEL, IMMOBILITY, THROMBOTIC EVENTS, OTHER PREGNANCY PROBLEMS (YES/NO), OTHER PREGNANCY PROBLEMS LIMITED TO THOSE IDENTIFIED AS BEING RISK FACTORS FOR PE, AND RECEIVED THROMBOPROPHYLAXIS

**Comments**

* I count eight items under "Previous Medical History" (based on the [database specification](https://docs.google.com/spreadsheets/d/15QgKTJL-9xdPgdkwNkimOnz0jeqIfnHpq7GCe9j84UE/edit#gid=0)), `history_thrombosis` (Family History of Thrombosis), `history_veins` (History of varicose veins) `history_iv_drug` (History of IV drug abuse), `thrombo` (Known Thrombophilia), `Surgery` (Surgery in the previous 4 weeks), `thrombosis` (Past history of thrombosis), `medical_probs` (Other previous or pre-existing medical problems).  All eight are summarised.
* I have interpreted `THROMBOTIC EVENTS` in the above text to equate to ???
* I do not know what constitutes `OTHER PREGNANCY PROBLEMS LIMITED TO THOSE IDENTIFIED AS BEING RISK FACTORS FOR PE` and have therefore opted to use the specific categories for which details are recorded under `this_pregnancy_problems`.
* Previous pregnancies are recorded as the number < 24 weeks and the number > 24 weeks.  Since the table description above only asks about the number of previous pregnancies they have been summed and are presented in conjunction with the constituents.
* I have taken the liberty of including the dichotomisation of all other continuous variables in this table as they are not noted to be tabulated anywhere else.
* **IMPORTANT**  Missing is not present for the many categories because of the stated way in which missing is to be handled.  Many fields are recorded in Prospect as `Ticked` (for `Yes`/ a positive response) and `Not Ticked` (for `No` / a negative response) and I was told to treat missing as `Not Ticked`, similarly for continuous variables where for example oxygen saturation is not recorded I was told to treat it as normal, and whilst a numerical value could not be provided as to what constitutes normal on the continuos scale, when it comes to dichotomising the variable this is implicit and the individual is categorised as `Normal` or `Low` risk.

```{r table_status_demographics1, echo = FALSE, warning = FALSE, messages = FALSE, eval = TRUE}
to.table <- dplyr::filter(dipep,
                          !is.na(first.st)) %>%
            dplyr::select(screening, first.st,
                          age.cat,
                          bmi.cat,
                          bp.systolic.cat,
                          bp.diastolic.cat,
                          o2.saturation.cat,
                          heart.rate.cat,
                          respiratory.rate.cat,
                          smoking,
                          pregnancies.over,
                          pregnancies.under,
                          prev.preg.problem,
                          history.thrombosis,
                          history.veins,
                          history.iv.drug,
                          thrombo,
                          surgery,
                          injury,
                          thrombosis,
                          medical.probs,
                          multiple.preg,
                          travel,
                          immobil,
                          thromb.event,
                          this.pregnancy.problems,
                          this.pregnancy.problems.dehydration,
                          this.pregnancy.problems.eclampsia,
                          this.pregnancy.problems.gestational.diabetes,
                          this.pregnancy.problems.haemorrhage,
                          this.pregnancy.problems.hyperemesis,
                          this.pregnancy.problems.ovarian.hyperstimulation,
                          this.pregnancy.problems.postpartum.haemorrhage,
                          this.pregnancy.problems.preeclampsia,
                          this.pregnancy.problems.preterm,
                          this.pregnancy.problems.severe.infection,
                          this.pregnancy.problems.stillbirth,
                          thromboprophylaxis)%>%
            mutate(previous.pregnancies = pregnancies.under + pregnancies.over) %>%
            gather(key = response, value = value, age.cat:previous.pregnancies)
table_status_demographics1 <- to.table %>%
                              group_by(first.st, response, value) %>%
                              summarise(n = n()) %>%
                              ungroup() %>%
                              mutate(percent   = case_when(.$first.st == 'PE'    ~ (100 * .$n) / n.pe,
                                                           .$first.st == 'No PE' ~ (100 * .$n) / n.no.pe),
                                     n_percent = paste0(formatC(n, format = 'f', digits = 0),
                                                        ' (',
                                                        formatC(percent, format = 'f', digits = digits.percent),
                                                        '%)')) %>%
                              dplyr::select(-n, -percent) %>%
                              spread(key = first.st, value = n_percent) %>%
                              mutate(variable = case_when(.$response == 'age.cat' ~ 'Age',
                                                          .$response == 'bmi.cat' ~ 'BMI',
                                                          .$response == 'bp.systolic.cat' ~ 'Systolic blood pressure',
                                                          .$response == 'bp.diastolic.cat' ~ 'Diastolic blood pressure',
                                                          .$response == 'o2.saturation.cat' ~ 'Oxygen saturation',
                                                          .$response == 'heart.rate.cat' ~ 'Heart rate',
                                                          .$response == 'respiratory.rate.cat' ~ 'Respiratory rate',
                                                          .$response == 'smoking' ~ 'Smoking',
                                                          .$response == 'pregnancies.over' ~ 'Pregnancies > 24 weeks',
                                                          .$response == 'pregnancies.under' ~ 'Pregnancies < 24 weeks',
                                                          .$response == 'pregnancies.pregnancies' ~ 'Previous pregnancies',
                                                          .$response == 'prev.preg.problem' ~ 'Problems with previous pregnancies',
                                                          .$response == 'history.thrombosis' ~ 'History of thrombosis in first degree relatives',
                                                          .$response == 'history.veins' ~ 'History of varicose veins',
                                                          .$response == 'history.iv.drug' ~ 'History of IV drug abuse',
                                                          .$response == 'thrombo' ~ '',
                                                          .$response == 'surgery' ~ 'Surgery in the previous 4 weeks.',
                                                          .$response == 'injury' ~ 'Significant injury in the previous 4 weeks',
                                                          .$response == 'thrombosis' ~ 'Past history of thrombosis.',
                                                          .$response == 'medical.probs' ~ 'Previous or pre-existing medical problems',
                                                          .$response == 'multiple.preg' ~ 'Multiple pregnancy',
                                                          .$response == 'travel' ~ '> 4 hrs flight during this pregnancy',
                                                          .$response == 'immobil' ~ '> 3 days immobility/bed rest during this pregnancy',
                                                          .$response == 'thromb_event' ~ 'Previous thrombotic event in This Pregnancy',
                                                          .$response == 'this.pregnancy.problems' ~ 'Problems with this pregnancy',
                                                          .$response == 'this.pregnancy.problems.dehydration' ~ 'Dehydration',
                                                          .$response == 'this.pregnancy.problems.eclampsia' ~ 'Eclampsia',
                                                          .$response == 'this.pregnancy.problems.gestational.diabetes' ~ 'Gestational Diabetes',
                                                          .$response == 'this.pregnancy.problems.haemorrhage' ~ 'Haemorrhage',
                                                          .$response == 'this.pregnancy.problems.hyperemesis' ~ 'Hyperemesis',
                                                          .$response == 'this.pregnancy.problems.ovarian.hyperstimulation' ~ '',
                                                          .$response == 'this.pregnancy.problems.postpartum.haemorrhage' ~ '',
                                                          .$response == 'this.pregnancy.problems.preeclampsia' ~ 'Preeclampsia',
                                                          .$response == 'this.pregnancy.problems.preterm' ~ 'Pre-Term Birth',
                                                          .$response == 'this.pregnancy.problems.severe.infection' ~ 'Severe Infection',
                                                          .$response == 'this.pregnancy.problems.stillbirth' ~ 'Stillbirth',
                                                          .$response == 'thromboprophylaxis' ~ 'Thromboprophylaxis')) %>%
                              group_by(variable) %>%
                              mutate(id = 1:n(),
                                     response = ifelse(id == 1,
                                                       yes = variable,
                                                       no  = '')) %>%
                              ungroup() %>%
                              dplyr::select(response, value, `No PE`, PE)
kable(table_status_demographics1,
      caption = 'Categorised PE status',
      col.names = c('Question', 'Response',
                    head.no.pe, head.pe))

```
