#' Field Descriptions
#'
#' @description Descriptions of fields (variables) in the Dipep dataset
#'
#' @details
#' Variable names are sometimes informative, sometimes cryptic.  To avoid this each data frames
#' variables are described using the database specification produced by Data Management.
#'
#' @param df The data frame who's variables need describing
#' @param fields A data frame that contains the information from the database specification
#'               spreadsheet produced by Data Management. It should have a bare minimum of two
#'               columns the 'Identifier' column (normally column D) and the 'Label' column
#'               (usually column E) and these should be named \code{variable} and
#'               \code{description} respectively.
#'
#' @export
fields_dipep <- function(df      = master$follow.up.30.day,
                         fields  = fields){
    ## Get the dataframes variable names and merge with the fields data frame
    names.df <- names(df) %>%
        data.frame()
    names(names.df) <- c("variable")
    names.df <- merge(names.df,
                      fields,
                      by    = 'variable',
                      all.x = TRUE)
    ## Additional fields not documented (e.g. from forms/fields or derived variable)
    names.df$description[names.df$variable == 'event.name']                                       <- 'Event Name'
    names.df$description[names.df$variable == 'event.date']                                       <- 'Event Date'
    names.df$description[names.df$variable == 'form.name']                                        <- 'Form Name'
    names.df$description[names.df$variable == 'group']                                            <- 'Group (Suspected PE/)'
    names.df$description[names.df$variable == 'identifier']                                       <- 'identifier'
    names.df$description[names.df$variable == 'identifier']                                       <- 'identifier'
    names.df$description[names.df$variable == 'wells.alternative.permissive']                     <- 'Wells  (Permissive) - Alternative Diagnosis'
    names.df$description[names.df$variable == 'wells.alternative.strict']                         <- 'Wells (Strict) - Alternative Diagnosis'
    names.df$description[names.df$variable == 'wells.dvt']                                        <- 'Wells - Clinical DVT'
    names.df$description[names.df$variable == 'wells.dvt.pe']                                     <- 'Wells - Previous DVT/PE'
    names.df$description[names.df$variable == 'wells.haemoptysis']                                <- 'Wells - Haemoptysis'
    names.df$description[names.df$variable == 'wells.heart.rate']                                 <- 'Wells - Heart Rate'
    names.df$description[names.df$variable == 'wells.immobil']                                    <- 'Wells - Immobility'
    names.df$description[names.df$variable == 'wells.neoplasm']                                   <- 'Wells - Neoplasm'
    names.df$description[names.df$variable == 'wells.permissive']                                 <- 'Wells (Permissive) - Score'
    names.df$description[names.df$variable == 'wells.permissive.pe']                              <- 'Wells (Permissive) - Binary'
    names.df$description[names.df$variable == 'wells.permissive.risk']                            <- 'Wells (Permissive) - Risk'
    names.df$description[names.df$variable == 'wells.strict']                                     <- 'Wells (Strict) - Score'
    names.df$description[names.df$variable == 'wells.strict.pe']                                  <- 'Wells (Strict)- Binary'
    names.df$description[names.df$variable == 'wells.strict.risk']                                <- 'Wells (Strict) - Risk'
    names.df$description[names.df$variable == 'wells.surgery']                                    <- 'Wells - Surgery'
    names.df$description[names.df$variable == 'wells.surgery.immobil']                            <- 'Wells - Surgery/Immobility'
    names.df$description[names.df$variable == 'simplified']                                       <- 'Simplified Revised Geneva - Score'
    names.df$description[names.df$variable == 'simplified.age']                                   <- 'Simplified Revised Geneva - Age'
    names.df$description[names.df$variable == 'simplified.haemoptysis']                           <- 'Simplified Revised Geneva - Haemoptysis'
    names.df$description[names.df$variable == 'simplified.heart.rate']                            <- 'Simplified Revised Geneva - Heart Rate'
    names.df$description[names.df$variable == 'simplified.lower.limb.unilateral.pain']            <- 'Simplified Revised Geneva - Lower Limb Unilateral Pain'
    names.df$description[names.df$variable == 'simplified.neoplasm']                              <- 'Simplified Revised Geneva - Neoplasm'
    names.df$description[names.df$variable == 'simplified.pain.palpitations']                     <- 'Simplified Revised Geneva - Pain on Leg Palpitations'
    names.df$description[names.df$variable == 'simplified.pe']                                    <- 'Simplified Revised Geneva - Pulmonary Embolism (Binary)'
    names.df$description[names.df$variable == 'simplified.prev.dvt.pe']                           <- 'Simplified Revised Geneva - Previous DVT/PE'
    names.df$description[names.df$variable == 'simplified.risk']                                  <- 'Simplified Revised Geneva - Risk'
    names.df$description[names.df$variable == 'simplified.surgery']                               <- 'Simplified Revised Geneva - Surgery'
    names.df$description[names.df$variable == 'perc']                                             <- 'PERC - Score'
    names.df$description[names.df$variable == 'perc.age']                                         <- 'PERC - Age'
    names.df$description[names.df$variable == 'perc.haemoptysis']                                 <- 'PERC - Haemoptysis'
    names.df$description[names.df$variable == 'perc.heart.rate']                                  <- 'PERC - Heart Rate'
    names.df$description[names.df$variable == 'perc.hormone']                                     <- 'PERC - Horomone Therapy'
    names.df$description[names.df$variable == 'perc.leg.swelling']                                <- 'PERC - Unilateral Leg Swelling'
    names.df$description[names.df$variable == 'perc.o2']                                          <- 'PERC - O2 Saturation'
    names.df$description[names.df$variable == 'perc.pe']                                          <- 'PERC - Pulmonary Embolism (Binary)'
    names.df$description[names.df$variable == 'perc.prev.dvt.pe']                                 <- 'PERC - Previous DVT/PE'
    names.df$description[names.df$variable == 'perc.surgery']                                     <- 'PERC - Surgery'
    names.df$description[names.df$variable == 'delphi.primary.pe']                                <- 'Delphi (Primary) - Binary'
    names.df$description[names.df$variable == 'delphi.primary.bmi']                               <- 'Delphi (Primary) - BMI > 30'
    names.df$description[names.df$variable == 'delphi.primary.clinical.dvt']                      <- 'Delphi (Primary) - Clinical Signs of DVT'
    names.df$description[names.df$variable == 'delphi.primary.family.history']                    <- 'Delphi (Primary) - Family History of Thrombosis'
    names.df$description[names.df$variable == 'delphi.primary.gestation']                         <- 'Delphi (Primary) - Gestation'
    names.df$description[names.df$variable == 'delphi.primary.haemoptysis']                       <- 'Delphi (Primary) - Haemoptysis'
    names.df$description[names.df$variable == 'delphi.primary.heart.rate.100.bpm']                <- 'Delphi (Primary) - Heart Rate > 100bpm'
    names.df$description[names.df$variable == 'delphi.primary.heart.rate.110.bpm']                <- 'Delphi (Primary) - Heart Rate > 110bpm'
    names.df$description[names.df$variable == 'delphi.primary.history.dvt.pe']                    <- 'Delphi (Primary) - History of DVT/PE'
    names.df$description[names.df$variable == 'delphi.primary.history.iv.drug']                   <- 'Delphi (Primary) - History of IV Drug Use'
    names.df$description[names.df$variable == 'delphi.primary.medical.complication']              <- 'Delphi (Primary) - Medical Complication'
    names.df$description[names.df$variable == 'delphi.primary.medical.history']                   <- 'Delphi (Primary) - Medical History (admissions/surgery/significant injury)'
    names.df$description[names.df$variable == 'delphi.primary.o2.saturation']                     <- 'Delphi (Primary) - O2 Saturation'
    names.df$description[names.df$variable == 'delphi.primary.obstetric.complication']            <- 'Delphi (Primary) - Obstetric Complications'
    names.df$description[names.df$variable == 'delphi.primary.pleuritic']                         <- 'Delphi (Primary) - Pleuritic'
    names.df$description[names.df$variable == 'delphi.primary.respiratory.rate']                  <- 'Delphi (Primary) - Respiratory Rate > 20 breaths/min'
    names.df$description[names.df$variable == 'delphi.primary']                                   <- 'Delphi (Primary) - Score'
    names.df$description[names.df$variable == 'delphi.primary.syncope']                           <- 'Delphi (Primary) - Syncope'
    names.df$description[names.df$variable == 'delphi.sensitivity.pe']                            <- 'Delphi (Sensitivity) - Binary'
    names.df$description[names.df$variable == 'delphi.sensitivity.bmi']                           <- 'Delphi (Sensitivity) - BMI > 30'
    names.df$description[names.df$variable == 'delphi.sensitivity.clinical.dvt']                  <- 'Delphi (Sensitivity) - Clincal Signs of DVT'
    names.df$description[names.df$variable == 'delphi.sensitivity.family.history']                <- 'Delphi (Sensitivity) - Family History of Thrombosis'
    names.df$description[names.df$variable == 'delphi.sensitivity.gestation']                     <- 'Delphi (Sensitivity) - Gestation'
    names.df$description[names.df$variable == 'delphi.sensitivity.haemoptysis']                   <- 'Delphi (Sensitivity) - Haemoptysis'
    names.df$description[names.df$variable == 'delphi.sensitivity.heart.rate.100.bpm']            <- 'Delphi (Sensitivity) - Heart Rate > 100bpm'
    names.df$description[names.df$variable == 'delphi.sensitivity.heart.rate.110.bpm']            <- 'Delphi (Sensitivity) - Heart Rate > 110bpm'
    names.df$description[names.df$variable == 'delphi.sensitivity.history.dvt.pe']                <- 'Delphi (Sensitivity) - History of DVT/PE'
    names.df$description[names.df$variable == 'delphi.sensitivity.history.iv.drug']               <- 'Delphi (Sensitivity) - History of IV Drug Use'
    names.df$description[names.df$variable == 'delphi.sensitivity.medical.complication']          <- 'Delphi (Sensitivity) - Medical Complications'
    names.df$description[names.df$variable == 'delphi.sensitivity.medical.history']               <- 'Delphi (Sensitivity) - Medical History (admissions/surgery/significant injury)'
    names.df$description[names.df$variable == 'delphi.sensitivity.o2.saturation']                 <- 'Delphi (Sensitivity) - O2 Saturation'
    names.df$description[names.df$variable == 'delphi.sensitivity.obstetric.complication']        <- 'Delphi (Sensitivity) - Obstetric Complication'
    names.df$description[names.df$variable == 'delphi.sensitivity.pleuritic']                     <- 'Delphi (Sensitivity) - Pleuritic'
    names.df$description[names.df$variable == 'delphi.sensitivity.respiratory.rate']              <- 'Delphi (Sensitivity) - Respiratyr Rate > 20 breahs/min'
    names.df$description[names.df$variable == 'delphi.sensitivity']                               <- 'Delphi (Sensitivity) - Score'
    names.df$description[names.df$variable == 'delphi.sensitivity.syncope']                       <- 'Delphi (Sensitivity) - Syncope'
    names.df$description[names.df$variable == 'delphi.specificity.pe']                            <- 'Delphi (Specificity) - Binary'
    names.df$description[names.df$variable == 'delphi.specificity.bmi']                           <- 'Delphi (Specificity) - BMI > 30'
    names.df$description[names.df$variable == 'delphi.specificity.clinical.dvt']                  <- 'Delphi (Specificity) - Clinical Signs of DVT'
    names.df$description[names.df$variable == 'delphi.specificity.family.history']                <- 'Delphi (Specificity) - Family History of Thrombosis'
    names.df$description[names.df$variable == 'delphi.specificity.gestation']                     <- 'Delphi (Specificity) - Gestation'
    names.df$description[names.df$variable == 'delphi.specificity.haemoptysis']                   <- 'Delphi (Specificity) - Haemoptysis'
    names.df$description[names.df$variable == 'delphi.specificity.heart.rate.100.bpm']            <- 'Delphi (Specificity) - Heart Rate > 100bpm'
    names.df$description[names.df$variable == 'delphi.specificity.heart.rate.110.bpm']            <- 'Delphi (Specificity) - Heart Rate > 110bpm'
    names.df$description[names.df$variable == 'delphi.specificity.history.dvt.pe']                <- 'Delphi (Specificity) - History of DVT/PE'
    names.df$description[names.df$variable == 'delphi.specificity.history.iv.drug']               <- 'Delphi (Specificity) - History of IV Drug Use'
    names.df$description[names.df$variable == 'delphi.specificity.medical.complication']          <- 'Delphi (Specificity) - Medical Complications'
    names.df$description[names.df$variable == 'delphi.specificity.medical.history']               <- 'Delphi (Specificity) - Medical History (admissions/surgery/significant injury)'
    names.df$description[names.df$variable == 'delphi.specificity.o2.saturation']                 <- 'Delphi (Specificity) - O2 Saturation'
    names.df$description[names.df$variable == 'delphi.specificity.obstetric.complication']        <- 'Delphi (Specificity) - Obstetric Complications'
    names.df$description[names.df$variable == 'delphi.specificity.pleuritic']                     <- 'Delphi (Specificity) - Pleuritic'
    names.df$description[names.df$variable == 'delphi.specificity.respiratory.rate']              <- 'Delphi (Specificity) - Respiratory Rate > 20 breaths/min'
    names.df$description[names.df$variable == 'delphi.specificity']                               <- 'Delphi (Specificity) - Score'
    names.df$description[names.df$variable == 'delphi.specificity.syncope']                       <- 'Delphi (Specificity) - Syncope'
    names.df$description[names.df$variable == 'aptt']                                             <- ''
    names.df$description[names.df$variable == 'aptt.cat']                                         <- ''
    names.df$description[names.df$variable == 'bnp']                                              <- ''
    names.df$description[names.df$variable == 'bnp.cat']                                          <- ''
    names.df$description[names.df$variable == 'clauss.fibrinogen.cat']                            <- ''
    names.df$description[names.df$variable == 'crp']                                              <- ''
    names.df$description[names.df$variable == 'crp.cat']                                          <- ''
    names.df$description[names.df$variable == 'd.dimer.cat']                                      <- ''
    names.df$description[names.df$variable == 'd.dimer.gestation.cat']                            <- ''
    names.df$description[names.df$variable == 'ddimer.elisa.cat']                                 <- ''
    names.df$description[names.df$variable == 'ddimer.innovance']                                 <- 'D-Dimer - Innovance'
    names.df$description[names.df$variable == 'ddimer.innovance.cat']                             <- 'D-Dimer - Innovance (Categorised)'
    names.df$description[names.df$variable == 'delphi.bmi']                                       <- 'Delphi Consensus Clinical Decision Rule Component - BMI'
    names.df$description[names.df$variable == 'delphi.dvt']                                       <- 'Delphi Consensus Clinical Decision Rule Component - DVT'
    names.df$description[names.df$variable == 'delphi.family.history']                            <- 'Delphi Consensus Clinical Decision Rule Component - Family History'
    names.df$description[names.df$variable == 'delphi.gestation']                                 <- 'Delphi Consensus Clinical Decision Rule Component - Gestation'
    names.df$description[names.df$variable == 'delphi.haemoptysis']                               <- 'Delphi Consensus Clinical Decision Rule Component - Haemoptysis'
    names.df$description[names.df$variable == 'delphi.heart.rate']                                <- 'Delphi Consensus Clinical Decision Rule Component - Heart Rate'
    names.df$description[names.df$variable == 'delphi.history.dvt.pe']                            <- 'Delphi Consensus Clinical Decision Rule Component - DVT/PE'
    names.df$description[names.df$variable == 'delphi.medical.complication']                      <- 'Delphi Consensus Clinical Decision Rule Component - Medical Complications'
    names.df$description[names.df$variable == 'delphi.medical.history']                           <- 'Delphi Consensus Clinical Decision Rule Component - Medical History'
    names.df$description[names.df$variable == 'delphi.medical.history.injury']                    <- 'Delphi Consensus Clinical Decision Rule Component - Medical History (Injury)'
    names.df$description[names.df$variable == 'delphi.medical.history.surgery']                   <- 'Delphi Consensus Clinical Decision Rule Component - Medical History (Surgery)'
    names.df$description[names.df$variable == 'delphi.o2.saturation']                             <- 'Delphi Consensus Clinical Decision Rule Component - O2 Saturation'
    names.df$description[names.df$variable == 'delphi.obstetric.complication']                    <- 'Delphi Consensus Clinical Decision Rule Component - Obstetric Complications'
    names.df$description[names.df$variable == 'delphi.pleuritic']                                 <- 'Delphi Consensus Clinical Decision Rule Component - Pleuritic'
    names.df$description[names.df$variable == 'delphi.respiratory.rate']                          <- 'Delphi Consensus Clinical Decision Rule Component - Respiratory Rate'
    names.df$description[names.df$variable == 'delphi.thromb.event']                              <- 'Delphi Consensus Clinical Decision Rule Component - Thrombotic Event'
    names.df$description[names.df$variable == 'delphi.thrombosis']                                <- 'Delphi Consensus Clinical Decision Rule Component - Thrombosis'
    names.df$description[names.df$variable == 'diagonsis.post.pe']                                <- 'Diagnosis Post-PE assessment'
    names.df$description[names.df$variable == 'dvt.cat']                                          <- 'DVT Categorisation'
    names.df$description[names.df$variable == 'ecg.pe']                                           <- 'ECG show PE related problem'
    names.df$description[names.df$variable == 'existing.medical.cancer']                          <- 'Existing Neoplasm'
    names.df$description[names.df$variable == 'first.st.vte']                                     <- 'Primary Classification of VTE (Derived by Statistics)'
    names.df$description[names.df$variable == 'fourth.st.vte']                                    <- 'Quaternary Classification of VTE (Derived by Statistics)'
    names.df$description[names.df$variable == 'hyperemesis']                                      <- 'Hyperemesis'
    names.df$description[names.df$variable == 'likely.diagnosis']                                 <- 'Most likely Diagnosis'
    names.df$description[names.df$variable == 'med.hist.exclude']                                 <- 'Exclude on the basis of Medical History fields'
    names.df$description[names.df$variable == 'med.hist.miss.n']                                  <- 'Number of Medical History fields missing'
    names.df$description[names.df$variable == 'medical.comorbidity']                              <- 'Medical Comorbidity'
    names.df$description[names.df$variable == 'medical.complication']                             <- 'Medical Complications'
    names.df$description[names.df$variable == 'medical.other.dvt.pe']                             <- 'Medical Other - DVT/PE'
    names.df$description[names.df$variable == 'missing.exclude']                                  <- 'Exclude on the basis of "excessive" missing data'
    names.df$description[names.df$variable == 'mrproanp.cat']                                     <- 'MRProANP (Categorised)'
    names.df$description[names.df$variable == 'obstetric.complication']                           <- 'Obstetric Complication'
    names.df$description[names.df$variable == 'obstetric.complications']                          <- 'Obstetric Complication'
    names.df$description[names.df$variable == 'physiology.exclude']                               <- 'Exclude on the basis of missing Physiology fields'
    names.df$description[names.df$variable == 'physiology.miss.n']                                <- 'Number of Physiology fields missing'
    names.df$description[names.df$variable == 'plasmin.antiplasmin.cat']                          <- ' (Categorised)'
    names.df$description[names.df$variable == 'pregnancy.exclude']                                <- 'Exclude on the basis of missing This Pregnancy fields'
    names.df$description[names.df$variable == 'pregnancy.miss.n']                                 <- 'Number of This Pregnancy fields missing'
    names.df$description[names.df$variable == 'prothombin.time.cat']                              <- 'Prothombin Time (Categorised)'
    names.df$description[names.df$variable == 'prothrombin.fragments.cat']                        <- 'Prothrombin Fragments (Categorised)'
    names.df$description[names.df$variable == 'raw.med.hist.exclude']                             <- 'Exclude on the basis of missing Medical History fields missing (RAW prior to imputation of missing)'
    names.df$description[names.df$variable == 'raw.med.hist.miss.n']                              <- 'Number of Medical History fields missing (RAW prior to imputation of missing)'
    names.df$description[names.df$variable == 'raw.missing.exclude']                              <- 'Exclude on the basis of missing data (RAW prior to imputation of missing)'
    names.df$description[names.df$variable == 'raw.physiology.exclude']                           <- 'Exclude on the basis of missing Physiology fields missing (RAW prior to imputation of missing)'
    names.df$description[names.df$variable == 'raw.physiology.miss.n']                            <- 'Number of Physiology fields missing (RAW prior to imputation of missing)'
    names.df$description[names.df$variable == 'raw.pregnancy.exclude']                            <- 'Exclude on the basis of missing This Pregnancy fields missing (RAW prior to imputation of missing)'
    names.df$description[names.df$variable == 'raw.pregnancy.miss.n']                             <- 'Number of This Pregnancy fields missing (RAW prior to imputation of missing)'
    names.df$description[names.df$variable == 'second.st.vte']                                    <- 'Secondary Classification of VTE (Derived by Statistics)'
    names.df$description[names.df$variable == 'third.st.vte']                                     <- 'Tertiary Classification of VTE (Derived by Statistics)'
    names.df$description[names.df$variable == 'this.preg.problem.other_1']                        <- 'Problems with this Pregnancy Other - Record 1'
    names.df$description[names.df$variable == 'this.preg.problem.other_2']                        <- 'Problems with this Pregnancy Other - Record 2'
    names.df$description[names.df$variable == 'this.preg.problem.other_3']                        <- 'Problems with this Pregnancy Other - Record 3'
    names.df$description[names.df$variable == 'this.preg.problem.other_4']                        <- 'Problems with this Pregnancy Other - Record 4'
    names.df$description[names.df$variable == 'this.preg.problem.other_5']                        <- 'Problems with this Pregnancy Other - Record 5'
    names.df$description[names.df$variable == 'this.preg.problem.specify_1']                      <- 'Problems with this Pregnancy Specify - Record 1'
    names.df$description[names.df$variable == 'this.preg.problem.specify_2']                      <- 'Problems with this Pregnancy Specify - Record 2'
    names.df$description[names.df$variable == 'this.preg.problem.specify_3']                      <- 'Problems with this Pregnancy Specify - Record 3'
    names.df$description[names.df$variable == 'this.preg.problem.specify_4']                      <- 'Problems with this Pregnancy Specify - Record 4'
    names.df$description[names.df$variable == 'this.preg.problem.specify_5']                      <- 'Problems with this Pregnancy Specify - Record 5'
    names.df$description[names.df$variable == 'this.pregnancy.problems.dehydration']              <- 'Problems with this Pregnancy - Dehydration'
    names.df$description[names.df$variable == 'this.pregnancy.problems.eclampsia']                <- 'Problems with this Pregnancy - Eclampsia'
    names.df$description[names.df$variable == 'this.pregnancy.problems.gestational.diabetes']     <- 'Problems with this Pregnancy - Gestational Diabetes'
    names.df$description[names.df$variable == 'this.pregnancy.problems.haemorrhage']              <- 'Problems with this Pregnancy - Haemorrhage'
    names.df$description[names.df$variable == 'this.pregnancy.problems.hyperemesis']              <- 'Problems with this Pregnancy - Hyperemesis'
    names.df$description[names.df$variable == 'this.pregnancy.problems.incl.other']               <- 'Problems with this Pregnancy - Including Other'
    names.df$description[names.df$variable == 'this.pregnancy.problems.other']                    <- 'Problems with this Pregnancy - Other'
    names.df$description[names.df$variable == 'this.pregnancy.problems.ovarian.hyperstimulation'] <- 'Problems with this Pregnancy - Ovariatn Hyperstimulation'
    names.df$description[names.df$variable == 'this.pregnancy.problems.postpartum.haemorrhage']   <- 'Problems with this Pregnancy - Post-Partum Haemorrhage'
    names.df$description[names.df$variable == 'this.pregnancy.problems.preeclampsia']             <- 'Problems with this Pregnancy - Pre-Eclampsia'
    names.df$description[names.df$variable == 'this.pregnancy.problems.preterm']                  <- 'Problems with this Pregnancy - Pre-Term delivery'
    names.df$description[names.df$variable == 'this.pregnancy.problems.severe.infection']         <- 'Problems with this Pregnancy - Severe Infection'
    names.df$description[names.df$variable == 'this.pregnancy.problems.stillbirth']               <- 'Problems with this Pregnancy - Stillbirth'
    names.df$description[names.df$variable == 'thrombin.generation.endogenous.potential.cat']     <- 'Thrombin Generation Endogenous Potential (Categorised)'
    names.df$description[names.df$variable == 'thrombin.generation.lag.time.cat']                 <- 'Thrombin Generation Lag Time (Categorised)'
    names.df$description[names.df$variable == 'thrombin.generation.peak.cat']                     <- 'Thrombin Generation Peak (Categorised)'
    names.df$description[names.df$variable == 'thrombin.generation.time.to.peak.cat']             <- 'Thrombin Generation Time to Peak (Categorised)'
    names.df$description[names.df$variable == 'tissue.factor']                                    <- 'Tissue Factor'
    names.df$description[names.df$variable == 'tissue.factor.cat']                                <- 'Tissue Factor (Categorised)'
    names.df$description[names.df$variable == 'troponin.cat']                                     <- 'Troponin (Categorised)'
    names.df$description[names.df$variable == 'xray.pe']                                          <- 'X-Ray shows PE related problems'
    return(names.df)
}
