---
title: DiPEP - Statistical Report (Primary Analyses)
runtime: shiny
output: html_document
bibliography: sections/bibliography.bib
---

```{r setup, echo = FALSE, eval = TRUE}
##opts_chunk$set(dev = 'pdf')
opts_chunk$set(cache.path = 'cache/',
               width    = 200,
               fig.height = 8,
               fig.width  = 8,
               warning = FALSE,
               message = FALSE)
options(digits = 3)
## Ensure anchors are assessed first
## opts_knit$set(eval.after = 'echo')
## Hooks
## knit_hooks$set(anchor = hook_anchor)
## Set a seed
set.seed(69027181)
## Set sensible defaults
ggplot2.opts <- list()
ggplot2.opts$binwidth <- 30
## Exclusions
##
## The following 'non-recruited' need excluding from all analyses
exclusions <- c('N04/04', 'N04/05', 'N04/06')

```

```{r backup, echo = FALSE, eval = TRUE}
## Make a backup of current output based on time stamp by obtaining the
## modified time of the existing file and constructing a command to
## copy this to the sub-directory 'arch/' modifying the filename to include
## the timestamp
mtime <- gsub(' GMT', '', file.info('dipep.html')$mtime)
mtime <- gsub(' ', '-', mtime)
cmd <- paste0('cp dipep.html arch/dipep-', mtime, '.html && bzip2 arch/dipep-', mtime, '.html')
system(cmd)

```

```{r covariate_specification, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
classification <- 'first.st'
common <- c('pregnancies.over',
            'pregnancies.under',
            ## 'history.thrombosis',
            ## 'history.iv.drug',
            'history.veins',
            ## 'travel',
            ## 'multiple.preg',
            'prev.preg.problem',
            'presenting.features.pleuritic',
            'presenting.features.non.pleuritic',
            ## 'presenting.features.sob.exertion',
            'presenting.features.sob.rest',
            'presenting.features.haemoptysis',
            'presenting.features.cough',
            'presenting.features.syncope',
            'presenting.features.palpitations',
            'presenting.features.other',
            'surgery',
            'cesarean',
            'thromb.event',
            ## 'thromboprophylaxis',
            ## 'smoking',
            'thrombosis',
            ## 'preg.post',
            'multiple.preg',
            'ecg.pe',
            'xray.pe')
categorical <- c('age.cat',
                 'bmi.cat',
                 'temperature.cat',
                 'bp.diastolic.cat',
                 'bp.systolic.cat',
                 'o2.saturation.cat',
                 'respiratory.rate.cat',
                 'heart.rate.cat')
continuous  <- c('age',
                 'bmi',
                 'temperature',
                 'bp.diastolic',
                 'bp.systolic',
                 'o2.saturation',
                 'respiratory.rate',
                 'heart.rate')

```

```{r notifications, echo = FALSE, eval = TRUE}

```

# {.tabset .tabset-fade .tabset-pills}
## Overview

```{r child = 'sections/overview.Rmd', eval = TRUE}
```

## Methods {.tabset .tabset-fade .tabset-pills}

```{r child = 'sections/methods.Rmd', eval = TRUE}
```

<!--- Run all analyses --->
```{r child = 'sections/analysis.Rmd', eval = FALSE}
```

## Results {.tabset .tabset-fade .tabset-pills}
```{r child = 'sections/results.Rmd', eval = TRUE}
```

<!-- ## Playground {.tabset .tabset-fade .tabset-pills} -->
<!-- ```{r child = 'sections/playground.Rmd', eval = FALSE} -->
<!-- ``` -->


## Appendix   {.tabset .tabset-fade .tabset-pills}
```{r child = 'sections/appendix.Rmd', eval = TRUE}
```

## References

<!-- # References -->
