---
title: HTA Report - Tables and Figures
output: word_document
bibliography: sections/bibliography.bib
---

```{r setup, echo = FALSE, eval = TRUE}
##opts_chunk$set(dev = 'pdf')
opts_chunk$set(cache.path = 'cache/',
               width    = 200,
               fig.height = 8,
               fig.width  = 8,
               warning = FALSE,
               message = FALSE)
options(digits = 1)
digits <- 1
digits.percent <- digits
## Ensure anchors are assessed first
## opts_knit$set(eval.after = 'echo')
## Hooks
## knit_hooks$set(anchor = hook_anchor)
## Set a seed
set.seed(69027181)
## Set sensible defaults
ggplot2.opts <- list()
ggplot2.opts$binwidth <- 30
## Exclusions
##
## The following 'non-recruited' need excluding from all analyses
exclusions <- c('N04/04', 'N04/05', 'N04/06')
## Knitr options
options(knitr.kable.NA = '-')

```

```{r backup, echo = FALSE, eval = TRUE}
## Make a backup of current output based on time stamp by obtaining the
## modified time of the existing file and constructing a command to
## copy this to the sub-directory 'arch/' modifying the filename to include
## the timestamp
mtime <- gsub(' GMT', '', file.info('hta_report_statistics.docx')$mtime)
mtime <- gsub(' ', '-', mtime)
cmd <- paste0('cp hta_report_statistics.docx arch/hta_report_statistics-', mtime, '.docx && bzip2 arch/hta_report_statistics-', mtime, '.docx')
system(cmd)

```


# {.tabset .tabset-fade .tabset-pills}

```{r child = 'sections/overview.Rmd', eval = TRUE}
```

<!--- ## Methods {.tabset .tabset-fade .tabset-pills} --->

```{r child = 'sections/methods.Rmd', eval = FALSE}
```

```{r child = 'sections/tables.Rmd', eval = TRUE}
```

```{r child = 'sections/figures.Rmd', eval = TRUE}
```


## References

<!-- # References -->
