```{r results_existing_logistic, , echo = FALSE, cache = FALSE, warning = FALSE, message = FALSE, fig.height = 10, fig.width = 10, results = 'rmarkdown', eval = TRUE}
## Treating existing scores as continuous variables (bad idea as they are not!) and
## univariable logistic regression of all components of the existing scores have
## been requested.  These are performed here and results presented under each section.
##
## Continuous variable ROC plots...
simplified <- dipep_existing_sum(df                    = dipep,
                                 title                 = 'Simplified Revised Geneva',
                                 exclude               = NULL,
                                 exclude.non.recruited = TRUE,
                                 exclude.dvt           = TRUE,
                                 exclude.missing       = TRUE,
                                 first.st, simplified.pe, simplified)
wells.permissive <- dipep_existing_sum(df                    = dipep,
                                 title                 = 'Wells Score (Permissive)',
                                 exclude               = NULL,
                                 exclude.non.recruited = TRUE,
                                 exclude.dvt           = TRUE,
                                 exclude.missing       = TRUE,
                                 first.st, wells.permissive.pe, wells.permissive)
wells.strict <- dipep_existing_sum(df                    = dipep,
                                 title                 = 'Wells Score (Strict)',
                                 exclude               = NULL,
                                 exclude.non.recruited = TRUE,
                                 exclude.dvt           = TRUE,
                                 exclude.missing       = TRUE,
                                 first.st, wells.strict.pe, wells.strict)
perc <- dipep_existing_sum(df                    = dipep,
                                 title                 = 'PERC Score',
                                 exclude               = NULL,
                                 exclude.non.recruited = TRUE,
                                 exclude.dvt           = TRUE,
                                 exclude.missing       = TRUE,
                                 first.st, perc.pe, perc)
delphi.primary <- dipep_existing_sum(df                    = dipep,
                                 title                 = 'Delphi Primary Score',
                                 exclude               = NULL,
                                 exclude.non.recruited = TRUE,
                                 exclude.dvt           = TRUE,
                                 exclude.missing       = TRUE,
                                 first.st, delphi.primary.pe, delphi.primary)
delphi.sensitivity <- dipep_existing_sum(df                    = dipep,
                                 title                 = 'Delphi Sensitivity Score',
                                 exclude               = NULL,
                                 exclude.non.recruited = TRUE,
                                 exclude.dvt           = TRUE,
                                 exclude.missing       = TRUE,
                                 first.st, delphi.sensitivity.pe, delphi.sensitivity)
delphi.specificity <- dipep_existing_sum(df                    = dipep,
                                 title                 = 'Delphi Specificity Score',
                                 exclude               = NULL,
                                 exclude.non.recruited = TRUE,
                                 exclude.dvt           = TRUE,
                                 exclude.missing       = TRUE,
                                 first.st, delphi.specificity.pe, delphi.specificity)


```


```{r results_existing_logistic_components, , echo = FALSE, cache = FALSE, warning = FALSE, message = FALSE, fig.height = 10, fig.width = 10, results = 'rmarkdown', eval = TRUE}
existing <- list()
existing$simplified <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'simplified',
                                     model                 = 'Geneva',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$simplified.age <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'simplified.age',
                                     model                 = 'Geneva : Age (> 35)',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$simplified.prev.dvt.pe <- mutate(dipep,
                                          simplified.prev.dt.pe = ifelse(simplified.prev.dvt.pe == 3,
                                                                         yes = 1,
                                                                         no  = simplified.prev.dvt.pe)) %>%
                                   dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'simplified.prev.dvt.pe',
                                     model                 = 'Geneva : Previous DVT/PE',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$simplified.surgery <- mutate(dipep,
                                          simplified.surgery = ifelse(simplified.surgery == 3,
                                                                         yes = 1,
                                                                         no  = simplified.surgery)) %>%
                                   dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'simplified.surgery',
                                     model                 = 'Geneva : Surgery',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$simplified.neoplasm <- mutate(dipep,
                                       simplified.neoplasm = ifelse(simplified.neoplasm == 2,
                                                           yes = 1,
                                                           no  = simplified.neoplasm)) %>%
                                dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'simplified.neoplasm',
                                     model                 = 'Geneva : Neoplasm',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$simplified.lower.limb.unilateral.pain <- mutate(dipep,
                                                         simplified.lower.limb.unilateral.pain = ifelse(simplified.lower.limb.unilateral.pain == 3,
                                                                         yes = 1,
                                                                         no  = simplified.lower.limb.unilateral.pain)) %>%
                                                  dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'simplified.lower.limb.unilateral.pain',
                                     model                 = 'Geneva : Unilateral Lower Limb Pain',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$simplified.haemoptysis <- mutate(dipep,
                                          simplified.haemoptysis = ifelse(simplified.haemoptysis == 2,
                                                                          yes = 1,
                                                                          no  = simplified.haemoptysis)) %>%
                                   dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'simplified.haemoptysis',
                                     model                 = 'Geneva : Haemoptysis',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$simplified.heart.rate <- mutate(dipep,
                                       simplified.heart.rate = ifelse(simplified.heart.rate == 5,
                                                                      yes = 1,
                                                                      no  = simplified.heart.rate)) %>%
                                  dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'simplified.heart.rate',
                                     model                 = 'Geneva : Heart Rate',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$simplified.pain.palpitations <- mutate(dipep,
                                                simplified.pain.palpitations = ifelse(simplified.pain.palpitations == 5,
                                                                                      yes = 1,
                                                                                      no  = simplified.pain.palpitations)) %>%
                                         dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'simplified.pain.palpitations',
                                     model                 = 'Geneva : Pain on limb palpitation',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$perc <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'perc.pe',
                                     model                 = 'PERC',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$perc.age <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'perc.age',
                                     model                 = 'PERC : Age',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$perc.heart.rate <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'perc.heart.rate',
                                     model                 = 'PERC : Heart Rate',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$perc.o2 <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'perc.o2',
                                     model                 = 'PERC : O2 Saturation',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$perc.prev.dvt.pe <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'perc.prev.dvt.pe',
                                     model                 = 'PERC : Previous DVT/PE',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$perc.surgery <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'perc.surgery',
                                     model                 = 'PERC : Recent Trauma or Surgery',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$perc.haemoptysis <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'perc.haemoptysis',
                                     model                 = 'PERC : Haemoptysis',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$perc.hormone <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'perc.hormone',
                                     model                 = 'PERC : Exogenous Estrogen',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$perc.leg.swelling <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'perc.leg.swelling',
                                     model                 = 'PERC : Leg Swelling',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$wells.permissive <-  dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'wells.permissive.pe',
                                     model                 = 'Wells : Permissive',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$wells.strict <-  dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'wells.strict.pe',
                                     model                 = 'Wells : Strict',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$wells.dvt <- mutate(dipep,
                             wells.dvt = ifelse(wells.dvt == 3,
                                                yes = 1,
                                                no  = wells.dvt)) %>%
                      dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'wells.dvt',
                                     model                 = 'Wells : DVT',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$wells.alternative.permissive <- mutate(dipep,
                                                wells.alternative.permissive = ifelse(wells.alternative.permissive == 3,
                                                                   yes = 1,
                                                                   no  = wells.alternative.permissive)) %>%
                                         dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'wells.alternative.permissive',
                                     model                 = 'Wells : PE most likely diagnosis (Permissive)',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$wells.alternative.strict <- mutate(dipep,
                                                wells.alternative.strict = ifelse(wells.alternative.strict == 3,
                                                                   yes = 1,
                                                                   no  = wells.alternative.strict)) %>%
                                     dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'wells.alternative.strict',
                                     model                 = 'Wells : PE most likely diagnosis (Strict)',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$wells.heart.rate <- mutate(dipep,
                                    wells.heart.rate = ifelse(wells.heart.rate == 1.5,
                                                              yes = 1,
                                                              no  = wells.heart.rate)) %>%
                             dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'wells.heart.rate',
                                     model                 = 'Wells : Heart Rate',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$wells.surgery.immobil <- mutate(dipep,
                                         wells.surgery.immobil = ifelse(wells.surgery.immobil == 1.5,
                                                                        yes = 1,
                                                                        no  = wells.surgery.immobil)) %>%
                             dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'wells.surgery.immobil',
                                     model                 = 'Wells : Surgery/Immobility',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$wells.dvt.pe <- mutate(dipep,
                                wells.dvt.pe = ifelse(wells.dvt.pe == 1.5,
                                                      yes = 1,
                                                      no  = wells.dvt.pe)) %>%
                         dipep_glm(
                                     classification        = 'first.st',
                                     predictor             = 'wells.dvt.pe',
                                     model                 = 'Wells : DVT/PE',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$wells.haemoptysis <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'wells.haemoptysis',
                                     model                 = 'Wells : Haemoptysis',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$wells.neoplasm <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'wells.neoplasm',
                                     model                 = 'Wells : Neoplasm',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.primary <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.primary.pe',
                                     model                 = 'Delphi : Primary',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.sensitivity <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.sensitivity.pe',
                                     model                 = 'Delphi : Sensitivity',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.spceificity <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.specificity.pe',
                                     model                 = 'Delphi : Specificity',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.haemoptysis <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.haemoptysis',
                                     model                 = 'Delphi : Haemoptysis',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.pleuritic <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.pleuritic',
                                     model                 = 'Delphi : Pleuritic',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.history.dvt.pe <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.history.dvt.pe',
                                     model                 = 'Delphi : History of DVT/PE',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.family.history <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.family.history',
                                     model                 = 'Delphi : Family History',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.medical.history <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.medical.history',
                                     model                 = 'Delphi : Medical History (Hospital Admission, Surgery or Injury)',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.medical.history.surgery <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.medical.history.surgery',
                                     model                 = 'Delphi : Surgery (excl. Cesarean)',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.obstetric.complication <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.obstetric.complication',
                                     model                 = 'Delphi : Obstetric Complication',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.medical.complication <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.medical.complication',
                                     model                 = 'Delphi : Medical Complication',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.gestation <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.gestation',
                                     model                 = 'Delphi : Gestation',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.bmi <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.bmi',
                                     model                 = 'Delphi : BMI',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.dvt <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.dvt',
                                     model                 = 'Delphi : DVT',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.o2.saturation <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.o2.saturation',
                                     model                 = 'Delphi : O2 Saturation',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.heart.rate <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.heart.rate',
                                     model                 = 'Delphi : Heart Rate',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)
existing$delphi.respiratory.rate <- dipep_glm(df                    = dipep,
                                     classification        = 'first.st',
                                     predictor             = 'delphi.respiratory.rate',
                                     model                 = 'Delphi : Respiratory Rate',
                                     exclude               = NULL,
                                     exclude.dvt           = TRUE,
                                     exclude.non.recruited = TRUE,
                                     exclude.missing       = FALSE)

## Combine all thre sets of tidied output from each model
existing$tidied <- rbind(existing$simplified$tidied,
                         existing$simplified.age$tidied,
                         existing$simplified.prev.dvt.pe$tidied,
                         existing$simplified.surgery$tidied,
                         existing$simplified.neoplasm$tidied,
                         existing$simplified.lower.limb.unilateral.pain$tidied,
                         existing$simplified.haemoptysis$tidied,
                         existing$simplified.heart.rate$tidied,
                         existing$simplified.pain.palpitations$tidied,
                         existing$perc$tidied,
                         existing$perc.age$tidied,
                         existing$perc.heart.rate$tidied,
                         existing$perc.o2$tidied,
                         existing$perc.prev.dvt.pe$tidied,
                         existing$perc.surgery$tidied,
                         existing$perc.haemoptysis$tidied,
                         existing$perc.hormone$tidied,
                         existing$perc.leg.swelling$tidied,
                         existing$wells.permissive$tidied,
                         existing$wells.strict$tidied,
                         existing$wells.dvt$tidied,
                         existing$wells.alternative.permissive$tidied,
                         existing$wells.alternative.strict$tidied,
                         existing$wells.heart.rate$tidied,
                         existing$wells.surgery.immobil$tidied,
                         existing$wells.dvt.pe$tidied,
                         existing$wells.haemoptysis$tidied,
                         existing$wells.neoplasm$tidied,
                         existing$delphi.primary$tidied,
                         existing$delphi.sensitivity$tidied,
                         existing$delphi.specificity$tidied,
                         existing$delphi.haemoptysis$tidied,
                         existing$delphi.pleuritic$tidied,
                         existing$delphi.history.dvt.pe$tidied,
                         existing$delphi.family.history$tidied,
                         existing$delphi.medical.history$tidied,
                         existing$delphi.medical.history.surgery$tidied,
                         existing$delphi.obstetric.complication$tidied,
                         existing$delphi.medical.complication$tidied,
                         existing$delphi.gestation$tidied,
                         existing$delphi.bmi$tidied,
                         existing$delphi.dvt$tidied,
                         existing$delphi.o2.saturation$tidied,
                         existing$delphi.heart.rate$tidied,
                         existing$delphi.respiratory.rate$tidied)
existing$glance <- rbind(existing$simplified$glance,
                         existing$simplified.age$glance,
                         existing$simplified.prev.dvt.pe$glance,
                         existing$simplified.surgery$glance,
                         existing$simplified.neoplasm$glance,
                         existing$simplified.lower.limb.unilateral.pain$glance,
                         existing$simplified.haemoptysis$glance,
                         existing$simplified.heart.rate$glance,
                         existing$simplified.pain.palpitations$glance,
                         existing$perc$glance,
                         existing$perc.age$glance,
                         existing$perc.heart.rate$glance,
                         existing$perc.o2$glance,
                         existing$perc.prev.dvt.pe$glance,
                         existing$perc.surgery$glance,
                         existing$perc.haemoptysis$glance,
                         existing$perc.hormone$glance,
                         existing$perc.leg.swelling$glance,
                         existing$wells.permissive$glance,
                         existing$wells.strict$glance,
                         existing$wells.dvt$glance,
                         existing$wells.alternative.permissive$glance,
                         existing$wells.alternative.strict$glance,
                         existing$wells.heart.rate$glance,
                         existing$wells.surgery.immobil$glance,
                         existing$wells.dvt.pe$glance,
                         existing$wells.haemoptysis$glance,
                         existing$wells.neoplasm$glance,
                         existing$delphi.primary$glance,
                         existing$delphi.sensitivity$glance,
                         existing$delphi.specificity$glance,
                         existing$delphi.haemoptysis$glance,
                         existing$delphi.pleuritic$glance,
                         existing$delphi.history.dvt.pe$glance,
                         existing$delphi.family.history$glance,
                         existing$delphi.medical.history$glance,
                         existing$delphi.medical.history.surgery$glance,
                         existing$delphi.obstetric.complication$glance,
                         existing$delphi.medical.complication$glance,
                         existing$delphi.gestation$glance,
                         existing$delphi.bmi$glance,
                         existing$delphi.dvt$glance,
                         existing$delphi.o2.saturation$glance,
                         existing$delphi.heart.rate$glance,
                         existing$delphi.respiratory.rate$glance)
existing$predicted <- rbind(existing$simplified$predicted,
                         existing$simplified.age$predicted,
                         existing$simplified.prev.dvt.pe$predicted,
                         existing$simplified.surgery$predicted,
                         existing$simplified.neoplasm$predicted,
                         existing$simplified.lower.limb.unilateral.pain$predicted,
                         existing$simplified.haemoptysis$predicted,
                         existing$simplified.heart.rate$predicted,
                         existing$simplified.pain.palpitations$predicted,
                         existing$perc$predicted,
                         existing$perc.age$predicted,
                         existing$perc.heart.rate$predicted,
                         existing$perc.o2$predicted,
                         existing$perc.prev.dvt.pe$predicted,
                         existing$perc.surgery$predicted,
                         existing$perc.haemoptysis$predicted,
                         existing$perc.hormone$predicted,
                         existing$perc.leg.swelling$predicted,
                         existing$wells.permissive$predicted,
                         existing$wells.strict$predicted,
                         existing$wells.dvt$predicted,
                         existing$wells.alternative.permissive$predicted,
                         existing$wells.alternative.strict$predicted,
                         existing$wells.heart.rate$predicted,
                         existing$wells.surgery.immobil$predicted,
                         existing$wells.dvt.pe$predicted,
                         existing$wells.haemoptysis$predicted,
                         existing$wells.neoplasm$predicted,
                         existing$delphi.primary$predicted,
                         existing$delphi.sensitivity$predicted,
                         existing$delphi.specificity$predicted,
                         existing$delphi.pleuritic$predicted,
                         existing$delphi.history.dvt.pe$predicted,
                         existing$delphi.family.history$predicted,
                         existing$delphi.medical.history$predicted,
                         existing$delphi.medical.history.surgery$predicted,
                         existing$delphi.obstetric.complication$predicted,
                         existing$delphi.medical.complication$predicted,
                         existing$delphi.gestation$predicted,
                         existing$delphi.bmi$predicted,
                         existing$delphi.dvt$predicted,
                         existing$delphi.o2.saturation$predicted,
                         existing$delphi.heart.rate$predicted,
                         existing$delphi.respiratory.rate$predicted)
existing$cross.tab <- rbind(existing$simplified$table,
                         existing$simplified.age$table,
                         existing$simplified.prev.dvt.pe$table,
                         existing$simplified.surgery$table,
                         existing$simplified.neoplasm$table,
                         existing$simplified.lower.limb.unilateral.pain$table,
                         existing$simplified.haemoptysis$table,
                         existing$simplified.heart.rate$table,
                         existing$simplified.pain.palpitations$table,
                         existing$perc$table,
                         existing$perc.age$table,
                         existing$perc.heart.rate$table,
                         existing$perc.o2$table,
                         existing$perc.prev.dvt.pe$table,
                         existing$perc.surgery$table,
                         existing$perc.haemoptysis$table,
                         existing$perc.hormone$table,
                         existing$perc.leg.swelling$table,
                         existing$wells.permissive$table,
                         existing$wells.strict$table,
                         existing$wells.dvt$table,
                         existing$wells.alternative.permissive$table,
                         existing$wells.alternative.strict$table,
                         existing$wells.heart.rate$table,
                         existing$wells.surgery.immobil$table,
                         existing$wells.dvt.pe$table,
                         existing$wells.haemoptysis$table,
                         existing$wells.neoplasm$table,
                         existing$delphi.primary$table,
                         existing$delphi.sensitivity$table,
                         existing$delphi.specificity$table,
                         existing$delphi.haemoptysis$table,
                         existing$delphi.pleuritic$table,
                         existing$delphi.history.dvt.pe$table,
                         existing$delphi.family.history$table,
                         existing$delphi.medical.history$table,
                         existing$delphi.medical.history.surgery$table,
                         existing$delphi.obstetric.complication$table,
                         existing$delphi.medical.complication$table,
                         existing$delphi.gestation$table,
                         existing$delphi.bmi$table,
                         existing$delphi.dvt$table,
                         existing$delphi.o2.saturation$table,
                         existing$delphi.heart.rate$table,
                         existing$delphi.respiratory.rate$table)




```
