## Tables

```{r table_prep, echo = FALSE, warning = FALSE, messages = FALSE, eval = TRUE}
n.diagnosed.dvt <- dplyr::filter(dipep, group == 'Diagnosed DVT') %>% nrow()
n.diagnosed.pe  <- dplyr::filter(dipep, group == 'Diagnosed PE') %>% nrow()
n.non.recruited <- dplyr::filter(dipep, group == 'Non recruited') %>% nrow()
n.suspected.pe  <- dplyr::filter(dipep, group == 'Suspected PE') %>% nrow()
n.pe            <- dplyr::filter(dipep, first.st == 'PE'    & group %in% c('Suspected PE', 'Diagnosed PE')) %>% nrow()
n.no.pe         <- dplyr::filter(dipep, first.st == 'No PE' & group %in% c('Suspected PE', 'Diagnosed PE')) %>% nrow()
digits         <- 3
digits.percent <- digits
head.diagnosed.dvt <- paste0('Diagnosed DVT (N = ',
                             formatC(n.diagnosed.dvt, format = 'f', digits = 0),
                             ')')
head.diagnosed.pe  <- paste0('Diagnosed PE (N = ',
                             formatC(n.diagnosed.pe, format = 'f', digits = 0),
                             ')')

head.suspected.pe  <- paste0('Suspected PE (N = ',
                             formatC(n.suspected.pe, format = 'f', digits = 0),
                             ')')
head.non.recruited <- paste0('Non recruited (N = ',
                             formatC(n.non.recruited, format = 'f', digits = 0),
                             ')')
head.pe            <- paste0('PE (N = ',
                             formatC(n.pe, format = 'f', digits = 0),
                             ')')
head.no.pe         <- paste0('No PE (N = ',
                             formatC(n.no.pe, format = 'f', digits = 0),
                             ')')

## Load the results
load('../../knitr/data/dipep_results.RData')

```

```{r child = 'tables/recruitment_demographics1.Rmd', eval = TRUE}
```

```{r child = 'tables/recruitment_demographics2.Rmd', eval = TRUE}
```

```{r child = 'tables/recruitment_eq5d.Rmd', eval = TRUE}
```

```{r child = 'tables/status_demographics1.Rmd', eval = TRUE}
```

```{r child = 'tables/status_presenting.Rmd', eval = TRUE}
```

```{r child = 'tables/status_demographics2.Rmd', eval = TRUE}
```

```{r child = 'tables/logistic_table.Rmd', eval = TRUE}
```
